function [rawdata,brainshift,coregistration,normalization,preprocessing,reconstruction,prefs,stimulations,headmodel,ftracking,lead_mapper] = ea_create_bids_mapping()
%create a list of old files along with their full path:
%%
rawdata{:,1} = {'raw_anat_t1.nii';
    'raw_anat_t1.nii';
    'raw_anat_t1.nii';
    'raw_anat_t1.nii';    
    'raw_anat_t2.nii';
    'raw_anat_t2.nii';
    'raw_anat_t2.nii';
    'raw_anat_t2.nii';
    'raw_anat_pd.nii';
    'raw_anat_pd.nii';
    'raw_anat_pd.nii';
    'raw_anat_pd.nii';
    'raw_anat_flair.nii';
    'raw_anat_flair.nii';
    'raw_anat_flair.nii';
    'raw_anat_flair.nii';
    'raw_anat_fgatir.nii';
    'raw_anat_fgatir.nii';
    'raw_anat_fgatir.nii';
    'raw_anat_fgatir.nii';
    'raw_anat_t2star.nii';
    'raw_anat_t2star.nii';
    'raw_anat_t2star.nii';
    'raw_anat_t2star.nii';
    'raw_postop_ct.nii';
    'raw_postop_sag.nii';
    'raw_postop_tra.nii';
    'raw_postop_ax.nii';
    'raw_postop_cor.nii'};
rawdata{:,2} = {'ses-preop_acq-sag_T1w.nii.gz';
    'ses-preop_acq-cor_T1w.nii.gz';
    'ses-preop_acq-ax_T1w.nii.gz';
    'ses-preop_acq-iso_T1w.nii.gz';
    'ses-preop_acq-sag_T2w.nii.gz';
    'ses-preop_acq-cor_T2w.nii.gz';
    'ses-preop_acq-ax_T2w.nii.gz';
    'ses-preop_acq-iso_T2w.nii.gz';
    'ses-preop_acq-sag_PDw.nii.gz';
    'ses-preop_acq-cor_PDw.nii.gz';
    'ses-preop_acq-ax_PDw.nii.gz';
    'ses-preop_acq-iso_PDw.nii.gz';
    'ses-preop_acq-sag_FLAIR.nii.gz';
    'ses-preop_acq-cor_FLAIR.nii.gz';
    'ses-preop_acq-ax_FLAIR.nii.gz';
    'ses-preop_acq-iso_FLAIR.nii.gz';
    'ses-preop_acq-sag_FGATIR.nii.gz';
    'ses-preop_acq-cor_FGATIR.nii.gz';
    'ses-preop_acq-ax_FGATIR.nii.gz';
    'ses-preop_acq-iso_FGATIR.nii.gz';
    'ses-preop_acq-sag_T2starw.nii.gz';
    'ses-preop_acq-cor_T2starw.nii.gz';
    'ses-preop_acq-ax_T2starw.nii.gz';
    'ses-preop_acq-iso_T2starw.nii.gz';
    'ses-postop_CT.nii.gz';
    'ses-postop_acq-sag.nii.gz';
    'ses-postop_acq-ax.nii.gz';
    'ses-postop_acq-ax.nii.gz';
    'ses-postop_acq-cor.nii.gz'};

brainshift{:,1} = {'anat_t1.nii';
    'movim.nii';
    'bgmsk.nii';
    'bgmsk2.nii';
    'scrfmovim.nii';
    'scrf_instore.mat';
    'scrf_converted.mat';
    'scrf_instore_converted.mat';
    'standard.png';
    'scrf.png'};

brainshift{:,2} = {'ses-preop_space-anchorNative_rec-brainshift_desc-preproc_acqTag_T1w.nii';
    'ses-postop_space-anchorNative_rec-tonemapped_desc-preproc_CT.nii';
    'space-anchorNative_desc-secondstepmask.nii';
    'space-anchorNative_desc-thirdstepmask.nii';
    'ses-postop_space-anchorNative_rec-tonemappedbrainshift_desc-preproc_CT.nii';
    'from-anchorNative_to-anchorNativeBSC_desc-instore.mat';
    'from-anchorNative_to-anchorNativeBSC_desc-converted.mat';
    'from-anchorNative_to-anchorNativeBSC_desc-scrf.mat';
    'ses-preop_space-anchorNative_rec-brainshift_desc-preproc_acqTag_T1w.png';
    'ses-postop_space-anchorNative_rec-tonemappedbrainshift_desc-preproc_CT.png'};

coregistration{:,1} = {'rpostop_ct.nii';
    'postop_tra.nii';
    'postop_cor.nii';
    'postop_sag.nii';
    'anat_t1.nii';
    'anat_t2.nii';
    'anat_fgatir.nii';
    'anat_pd.nii';
    'anat_flair.nii';
    'anat_t2star.nii';
    'tp_rpostop_ct.nii';
    'fa2anat.nii';
    'c1anat_t1.nii';
    'c2anat_t1.nii';
    'c3anat_t1.nii';
    'ea_coreg_approved.mat';
    'ea_coregctmethod_applied.mat';
    'ea_coregmrmethod_applied.mat';
    'ea_precoregtransformation.mat';
    'anat_t12postop_ct_ants.mat';
    'anat_t12postop_ct_spm.mat';
    'postop_ct2anat_t1_ants.mat';
    'postop_ct2anat_t1_spm.mat';
    'anat_t12b0_ants.mat';
    'anat_t12b0_spm.mat';
    'b02anat_t1_ants.mat';
    'b02anat_t1_spm.mat';
    'anat_t22anat_t1.png';
    'anat_t2star2anat_t1.png';
    'anat_pd2anat_t1.png';
    'anat_flair2anat_t1.png';
    'anat_fgatir2anat_t1.png';
    'rpostop_ct2anat_t1.png';
    'tp_rpostop_ct2anat_t1.png';
    'tp_rpostop_ct2anat_t1_ea_coregctmri_ants.png';
    'postop_cor2anat_t1_SPM.png';
    'postop_cor2anat_t1_ANTs.png';
    'postop_cor2anat_t1_Hybrid SPM & BRAINSFIT';
    'postop_cor2anat_t1_Hybrid SPM & FSL';
    'postop_tra2anat_t1_SPM.png';
    'postop_tra2anat_t1_ANTs.png';
    'postop_tra2anat_t1_Hybrid SPM & BRAINSFIT';
    'postop_tra2anat_t1_Hybrid SPM & FSL';
    'postop_sag2anat_t1_SPM.png';
    'postop_sag2anat_t1_ANTs.png';
    'postop_sag2anat_t1_Hybrid SPM & BRAINSFIT';
    'postop_sag2anat_t1_Hybrid SPM & FSL'};
            
coregistration{:,2} = {'ses-postop_space-anchorNative_desc-preproc_CT.nii';
    'ses-postop_space-anchorNative_desc-preproc_acq-ax_MRI.nii';
    'ses-postop_space-anchorNative_desc-preproc_acq-cor_MRI.nii';
    'ses-postop_space-anchorNative_desc-preproc_acq-sag_MRI.nii';
    'ses-preop_space-anchorNative_desc-preproc_acqTag_T1w.nii';
    'ses-preop_space-anchorNative_desc-preproc_acqTag_T2w.nii';
    'ses-preop_space-anchorNative_desc-preproc_acqTag_FGATIR.nii';
    'ses-preop_space-anchorNative_desc-preproc_acqTag_PDw.nii';
    'ses-preop_space-anchorNative_desc-preproc_acqTag_FLAIR.nii';
    'ses-preop_space-anchorNative_desc-preproc_acqTag_T2starw.nii';
    'ses-postop_space-anchorNative_rec-tonemapped_desc-preproc_CT.nii';
    'ses-postop_space-anchorNative_desc-preproc_acq-fa.nii';
    'ses-preop_space-anchorNative_desc-preproc_acqTag_mod-T1w_label-GM_mask.nii';
    'ses-preop_space-anchorNative_desc-preproc_acqTag_mod-T1w_label-WM_mask.nii';
    'ses-preop_space-anchorNative_desc-preproc_acqTag_mod-T1w_label-CSF_mask.nii';
    'desc-coregmethod.mat';
    'desc-coregmethod.mat';
    'desc-coregmethod.mat';
    'desc-precoreg_T1w.mat';
    'from-anchorNative_to-CT_desc-ants.mat';
    'from-anchorNative_to-CT_desc-spm.mat';
    'from-CT_to-anchorNative_desc-ants.mat';
    'from-CT_to-anchorNative_desc-spm.mat';
    'from-anchorNative_to-b0_desc-ants.mat';
    'from-anchorNative_to-b0_desc-spm.mat';
    'from-b0_to-anchorNative_desc-ants.mat';
    'from-b0_to-anchorNative_desc-spm.mat';
    'ses-preop_space-anchorNative_desc-preproc_acqTag_T2w.png';
    'ses-preop_space-anchorNative_desc-preproc_acqTag_T2starw.png';
    'ses-preop_space-anchorNative_desc-preproc_acqTag_PDw.png';
    'ses-preop_space-anchorNative_desc-preproc_acqTag_FLAIR.png';
    'ses-preop_space-anchorNative_desc-preproc_acqTag_FGATIR.png';
    'ses-postop_space-anchorNative_desc-preproc_CT.png';
    'ses-postop_space-anchorNative_rec-tonemapped_desc-preproc_CT.png';
    'ses-postop_space-anchorNative_rec-tonemapped_desc-preproc_CT.png';
    'from-cor_to-anchorNative_desc-spm.png';
    'from-cor_to-anchorNative_desc-ants.png';
    'from-cor_to-anchorNative_desc-hybridspmbrainsfit.png';
    'from-cor_to-anchorNative_desc-hybridspmfsl.png';
    'from-ax_to-anchorNative_desc-spm.png';
    'from-ax_to-anchorNative_desc-ants.png';
    'from-ax_to-anchorNative_desc-hybridspmbrainsfit.png';
    'from-ax_to-anchorNative_desc-hybridspmfsl.png';
    'from-sag_to-anchorNative_desc-spm.png';
    'from-sag_to-anchorNative_desc-ants.png';
    'from-sag_to-anchorNative_desc-hybridspmbrainsfit.png';
    'from-sag_to-anchorNative_desc-hybridspmfsl.png'};
            
normalization{:,1}  = {'glpostop_ct.nii';
    'glpostop_tra.nii';
    'glpostop_cor.nii';
    'glpostop_sag.nii';
    'glanat_t1.nii';
    'glanat.nii';
    'tp_glpostop_ct.nii';
    'glfa2anat.nii';
    'glanat_fgatir.nii';
    'glanat_t2.nii';
    'glanat_pd.nii';
    'glanat_t2star.nii';
    'glanat_flair.nii';
    'glanat2t1_ea_normalize_ants.png';
    'glpostop_cor2t1_ea_normalize_ants.png';
    'glpostop_sag2t1_ea_normalize_ants.png';
    'glpostop_tra2t1_ea_normalize_ants.png';
    'glpostop_ct_ea_normalize_ants.png';
    'tp_glpostop_ct2t1_ea_normalize_ants.png';
    'ea_ants_command.txt';
    'ea_normmethod_applied.mat';
    'glanatComposite.nii.gz';
    'glanatInverseComposite.nii.gz';
    'glanatComposite.h5';
    'glanatInverseComposite.h5';
    'y_ea_normparams.nii';
    'y_ea_inv_normparams.nii'};
                   
normalization{:,2} = {'ses-postop_space-MNI152NLin2009bAsym_desc-preproc_CT.nii';
    'ses-postop_space-MNI152NLin2009bAsym_desc-preproc_acq-ax_MRI.nii';
    'ses-postop_space-MNI152NLin2009bAsym_desc-preproc_acq-cor_MRI.nii';
    'ses-postop_space-MNI152NLin2009bAsym_desc-preproc_acq-sag_MRI.nii';
    'ses-preop_space-MNI152NLin2009bAsym_desc-preproc_acqTag_T1w.nii';
    'ses-preop_space-MNI152NLin2009bAsym_desc-preproc_acqTag_T1w.nii';
    'ses-postop_space-MNI152NLin2009bAsym_rec-tonemapped_desc-preproc_CT.nii';
    'ses-preop_space-MNI152NLin2009bAsym_desc-preproc_fa.nii';
    'ses-preop_space-MNI152NLin2009bAsym_desc-preproc_acqTag_FGATIR.nii';
    'ses-preop_space-MNI152NLin2009bAsym_desc-preproc_acqTag_T2w.nii';
    'ses-preop_space-MNI152NLin2009bAsym_desc-preproc_acqTag_PDw.nii';
    'ses-preop_space-MNI152NLin2009bAsym_desc-preproc_acqTag_T2starw.nii';
    'ses-preop_space-MNI152NLin2009bAsym_desc-preproc_acqTag_FLAIR.nii';
    'ses-preop_space-MNI152NLin2009bAsym_desc-preproc_acqTag_T1w.png';
    'ses-postop_space-MNI152NLin2009bAsym_desc-preproc_acq-cor_MRI.png';
    'ses-postop_space-MNI152NLin2009bAsym_desc-preproc_acq-sag_MRI.png';
    'ses-postop_space-MNI152NLin2009bAsym_desc-preproc_acq-ax_MRI.png';
    'ses-postop_space-MNI152NLin2009bAsym_desc-preproc_CT.png';
    'ses-postop_space-MNI152NLin2009bAsym_rec-tonemapped_desc-preproc_CT.png';
    'desc-antscmd.txt';
    'desc-normmethod.mat';
    'from-anchorNative_to-MNI152NLin2009bAsym_desc-ants.nii.gz';
    'from-MNI152NLin2009bAsym_to-anchorNative_desc-ants.nii.gz';
    'from-anchorNative_to-MNI152NLin2009bAsym_desc-ants.nii.gz';
    'from-MNI152NLin2009bAsym_to-anchorNative_desc-ants.nii.gz';
    'from-anchorNative_to-MNI152NLin2009bAsym_desc-spm.nii';
    'from-MNI152NLin2009bAsym_to-anchorNative_desc-spm.nii'};

preprocessing{:,1} = {'postop_ct.nii';
    'raw_postop_tra.nii';
    'raw_postop_cor.nii';
    'raw_postop_sag.nii';
    'raw_anat_t1.nii';
    'raw_anat_t2.nii';
    'raw_anat_t2star.nii';
    'raw_anat_flair.nii';
    'raw_anat_fgatir.nii';
    'raw_anat_pd.nii';
    'raw_fa.nii'};
           
preprocessing{:,2} = {'ses-postop_desc-preproc_CT.nii';
    'ses-postop_desc-preproc_acq-ax_MRI.nii';
    'ses-postop_desc-preproc_acq-cor_MRI.nii';
    'ses-postop_desc-preproc_acq-sag_MRI.nii';
    'ses-preop_desc-preproc_acqTag_T1w.nii';
    'ses-preop_desc-preproc_acqTag_T2w.nii';
    'ses-preop_desc-preproc_acqTag_T2starw.nii';
    'ses-preop_desc-preproc_acqTag_FLAIR.nii';
    'ses-preop_desc-preproc_acqTag_FGATIR.nii';
    'ses-preop_desc-preproc_acqTag_PDw.nii';
    'ses-postop_desc-preproc_fa.nii'};

reconstruction{:,1} = {'ea_reconstruction.mat';
    'rct_mask.nii';
    'ct_mask.nii'};
reconstruction{:,2} = {'desc-reconstruction.mat';
    'space-anchorNative_desc-brainmask.nii';
    'space-rawCT_desc-brainmask.nii'};

%%
prefs{:,1} = {'ea_ui.mat'};
prefs{:,2} = {'desc-uiprefs.mat'};

log{:,1} = {'ea_methods.txt';'ea_stats.mat';'ea_stats_backup.mat'};
log{:,2} = {'desc-methods.txt';'desc-stats.mat';'desc-stats_backup.mat'};

stimulations{:,1} = {'fl_vat_left.nii';
    'fl_vat_right.nii';
    'fl_vat_efield_left.nii';
    'fl_vat_efield_right.nii';
    'vat_efield_gauss_left.nii';
    'vat_efield_gauss_right.nii';
    'vat_efield_left.nii';
    'vat_efield_right.nii';
    'vat_left.nii';
    'vat_right.nii';
    'vat_left.mat';
    'vat_right.mat';
    'vat_seed_compound_dMRI_l.nii';
    'vat_seed_compound_dMRI_r.nii';
    'vat_seed_compound_fMRI_l.nii';
    'vat_seed_compound_fMRI_r.nii';
    'vat_seed_compound_dMRI.nii';
    'vat_seed_compound_fMRI.nii';
    'vat_seed_compound_dMRI_efield_l.nii';
    'vat_seed_compound_dMRI_efield_r.nii';
    'vat_seed_compound_fMRI_efield_l.nii';
    'vat_seed_compound_fMRI_efield_r.nii';
    'vat_seed_compound_dMRI_efield.nii';
    'vat_seed_compound_fMRI_efield.nii'
    'vat_seed_compound_dMRI_efield_gauss_l.nii';
    'vat_seed_compound_dMRI_efield_gauss_r.nii';
    'vat_seed_compound_fMRI_efield_gauss_l.nii';
    'vat_seed_compound_fMRI_efield_gauss_r.nii';
    'vat_seed_compound_dMRI_efield_gauss.nii';
    'vat_seed_compound_fMRI_efield_gauss.nii';
    'stimparameters.mat'}; %deal with files inside connectome folder in the main code for now
                 
stimulations{:,2} = {'sim-binary_model-modelTag_hemi-R_hemidesc-FlippedFromLeft.nii';
    'sim-binary_model-modelTag_hemi-L_hemidesc-FlippedFromRight.nii';
    'sim-efield_model-modelTag_hemi-R_hemidesc-FlippedFromLeft.nii';
    'sim-efield_model-modelTag_hemi-L_hemidesc-FlippedFromRight.nii';
    'sim-efieldgauss_model-modelTag_hemi-L.nii';
    'sim-efieldgauss_model-modelTag_hemi-R.nii';
    'sim-efield_model-modelTag_hemi-L.nii';
    'sim-efield_model-modelTag_hemi-R.nii';
    'sim-binary_model-modelTag_hemi-L.nii';
    'sim-binary_model-modelTag_hemi-R.nii';
    'sim-binary_model-modelTag_hemi-L.mat';
    'sim-binary_model-modelTag_hemi-R.mat';
    'sim-binary_model-modelTag_seed-dMRI_hemi-L.nii';
    'sim-binary_model-modelTag_seed-dMRI_hemi-R.nii';
    'sim-binary_model-modelTag_seed-fMRI_hemi-L.nii';
    'sim-binary_model-modelTag_seed-fMRI_hemi-R.nii';
    'sim-binary_model-modelTag_seed-dMRI.nii';
    'sim-binary_model-modelTag_seed-fMRI.nii';
    'sim-efield_model-modelTag_seed-dMRI_hemi-L.nii';
    'sim-efield_model-modelTag_seed-dMRI_hemi-R.nii';
    'sim-efield_model-modelTag_seed-fMRI_hemi-L.nii';
    'sim-efield_model-modelTag_seed-fMRI_hemi-R.nii';
    'sim-efield_model-modelTag_seed-dMRI.nii';
    'sim-efield_model-modelTag_seed-fMRI.nii';
    'sim-efieldgauss_model-modelTag_seed-dMRI_hemi-L.nii';
    'sim-efieldgauss_model-modelTag_seed-dMRI_hemi-R.nii';
    'sim-efieldgauss_model-modelTag_seed-fMRI_hemi-L.nii';
    'sim-efieldgauss_model-modelTag_seed-fMRI_hemi-R.nii';
    'sim-efieldgauss_model-modelTag_seed-dMRI.nii';
    'sim-efieldgauss_model-modelTag_seed-fMRI.nii';
    'desc-stimparameters.mat'}; %deal with files inside connectome folder in the main code for now
    
lead_mapper{:,1} = {
    '_vat_seed_compound_dMRI_struc_seed.nii';
    '_vat_seed_compound_fMRI_func_seed_AvgR_Fz.nii';
    '_vat_seed_compound_fMRI_func_seed_AvgR.nii';
    '_vat_seed_compound_fMRI_func_seed_T.nii';
    '_vat_seed_compound_fMRI_func_seed_VarR.nii';
    '_vat_seed_compound_fMRI_func_seed_AvgR_Fz_surf_lh.nii';
    '_vat_seed_compound_fMRI_func_seed_AvgR_Fz_surf_rh.nii';
    '_vat_seed_compound_fMRI_func_seed_AvgR_surf_lh.nii';
    '_vat_seed_compound_fMRI_func_seed_AvgR_surf_rh.nii';
    '_vat_seed_compound_fMRI_func_seed_T_surf_lh.nii';
    '_vat_seed_compound_fMRI_func_seed_T_surf_rh.nii'};

lead_mapper{:,2} = {'sim-simTag_model-simbio_seed-dMRI_hemidesc-flippedTag_conn-conTag_strucmap.nii';
    'sim-simTag_model-modelTag_seed-fMRI_hemidesc-flippedTag_conn-conTag_desc-AvgRFz_funcmap.nii';
    'sim-simTag_model-modelTag_seed-fMRI_hemidesc-flippedTag_conn-conTag_desc-AvgR_funcmap.nii';
    'sim-simTag_model-modelTag_seed-fMRI_hemidesc-flippedTag_conn-conTag_desc-T_funcmap.nii';
    'sim-simTag_model-modelTag_seed-fMRI_hemidesc-flippedTag_conn-conTag_desc-VarR_funcmap.nii';
    'sim-simTag_model-modelTag_seed-fMRI_hemidesc-flippedTag_conn-conTag_hemi-L_desc-AvgRFz_funcmapsurf.nii';
    'sim-simTag_model-modelTag_seed-fMRI_hemidesc-flippedTag_conn-conTag_hemi-R_desc-AvgRFz_funcmapsurf.nii';
    'sim-simTag_model-modelTag_seed-fMRI_hemidesc-flippedTag_conn-conTag_hemi-L_desc-AvgR_funcmapsurf.nii';
    'sim-simTag_model-modelTag_seed-fMRI_hemidesc-flippedTag_conn-conTag_hemi-R_desc-AvgR_funcmapsurf.nii';
    'sim-simTag_model-modelTag_seed-fMRI_hemidesc-flippedTag_conn-conTag_hemi-L_desc-T_funcmapsurf.nii';
    'sim-simTag_model-modelTag_seed-fMRI_hemidesc-flippedTag_conn-conTag_hemi-R_desc-T_funcmapsurf.nii'};

headmodel{:,1} = {'headmodel1.mat';
    'headmodel2.mat';
    'hmprotocol1.mat';
    'hmprotocol2.mat'};

headmodel{:,2} = {'desc-headmodel1.mat';
    'desc-headmodel2.mat';
    'desc-hmprotocol1.mat';
    'desc-hmprotocol2.mat'};

ftracking{:,1} = {'b0.nii';
    'fa.nii';
    'FTR_anat.trk';
    'FTR_anat.mat';
    'ea_ftmethodapplied.mat';
    'ea_ftupsampling.mat';
    'FTR.trk';
    'FTR.mat';
    'FTR.fib.gz';
    'trackingmask.nii';
    'ttrackingmask.nii'};
ftracking{:,2} = { 'b0.nii';
    'fa.nii';
    'FTR_anat.trk';
    'FTR_anat.mat';
    'ea_ftmethodapplied.mat';
    'ea_ftupsampling.mat';
    'FTR.trk';
    'FTR.mat';
    'FTR.fib.gz';
    'trackingmask.nii';
    'ttrackingmask.nii'};


return 
end
