# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pop_up_ui/pop_up_Mesh_Refinement.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_centralwidget(object):
    def setupUi(self, centralwidget):
        centralwidget.setObjectName("centralwidget")
        centralwidget.resize(836, 450)
        centralwidget.setMaximumSize(QtCore.QSize(836, 450))
        centralwidget.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_Run_Close = QtWidgets.QWidget(centralwidget)
        font = QtGui.QFont()
        self.widget_Run_Close.setFont(font)
        self.widget_Run_Close.setObjectName("widget_Run_Close")
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout(self.widget_Run_Close)
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_57.addItem(spacerItem)
        self.pushButton_Save = QtWidgets.QPushButton(self.widget_Run_Close)
        font = QtGui.QFont()
        self.pushButton_Save.setFont(font)
        self.pushButton_Save.setStyleSheet("")
        self.pushButton_Save.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.horizontalLayout_57.addWidget(self.pushButton_Save)
        self.pushButton_Cancel = QtWidgets.QPushButton(self.widget_Run_Close)
        font = QtGui.QFont()
        self.pushButton_Cancel.setFont(font)
        self.pushButton_Cancel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_Cancel.setStyleSheet("")
        self.pushButton_Cancel.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.horizontalLayout_57.addWidget(self.pushButton_Cancel)
        self.gridLayout.addWidget(self.widget_Run_Close, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.widget = QtWidgets.QWidget(centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.doubleSpinBox_Rel_Div_Current = QtWidgets.QDoubleSpinBox(self.widget)
        font = QtGui.QFont()
        self.doubleSpinBox_Rel_Div_Current.setFont(font)
        self.doubleSpinBox_Rel_Div_Current.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.doubleSpinBox_Rel_Div_Current.setDecimals(4)
        self.doubleSpinBox_Rel_Div_Current.setMinimum(0.0)
        self.doubleSpinBox_Rel_Div_Current.setMaximum(10000000000000.0)
        self.doubleSpinBox_Rel_Div_Current.setProperty("value", 1.0)
        self.doubleSpinBox_Rel_Div_Current.setObjectName("doubleSpinBox_Rel_Div_Current")
        self.gridLayout_3.addWidget(self.doubleSpinBox_Rel_Div_Current, 8, 1, 1, 1)
        self.doubleSpinBox_Deviation_Threshold = QtWidgets.QDoubleSpinBox(self.widget)
        font = QtGui.QFont()
        self.doubleSpinBox_Deviation_Threshold.setFont(font)
        self.doubleSpinBox_Deviation_Threshold.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.doubleSpinBox_Deviation_Threshold.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.doubleSpinBox_Deviation_Threshold.setProperty("showGroupSeparator", False)
        self.doubleSpinBox_Deviation_Threshold.setDecimals(4)
        self.doubleSpinBox_Deviation_Threshold.setMinimum(-1000000000.0)
        self.doubleSpinBox_Deviation_Threshold.setMaximum(1000000000.0)
        self.doubleSpinBox_Deviation_Threshold.setProperty("value", 1.0)
        self.doubleSpinBox_Deviation_Threshold.setObjectName("doubleSpinBox_Deviation_Threshold")
        self.gridLayout_3.addWidget(self.doubleSpinBox_Deviation_Threshold, 4, 1, 1, 1)
        self.widget_Refinement_Frequencies = QtWidgets.QWidget(self.widget)
        self.widget_Refinement_Frequencies.setObjectName("widget_Refinement_Frequencies")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_Refinement_Frequencies)
        self.verticalLayout_6.setContentsMargins(20, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_Refinement_Frequency = QtWidgets.QLabel(self.widget_Refinement_Frequencies)
        font = QtGui.QFont()
        self.label_Refinement_Frequency.setFont(font)
        self.label_Refinement_Frequency.setIndent(30)
        self.label_Refinement_Frequency.setObjectName("label_Refinement_Frequency")
        self.verticalLayout_6.addWidget(self.label_Refinement_Frequency)
        self.gridLayout_3.addWidget(self.widget_Refinement_Frequencies, 2, 0, 1, 1)
        self.label_Deviation_Threshold_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        self.label_Deviation_Threshold_2.setFont(font)
        self.label_Deviation_Threshold_2.setObjectName("label_Deviation_Threshold_2")
        self.gridLayout_3.addWidget(self.label_Deviation_Threshold_2, 4, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 9, 4, 1, 1)
        self.doubleSpinBox_CSF_Ref_Reg = QtWidgets.QDoubleSpinBox(self.widget)
        font = QtGui.QFont()
        self.doubleSpinBox_CSF_Ref_Reg.setFont(font)
        self.doubleSpinBox_CSF_Ref_Reg.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.doubleSpinBox_CSF_Ref_Reg.setDecimals(4)
        self.doubleSpinBox_CSF_Ref_Reg.setMinimum(0.0)
        self.doubleSpinBox_CSF_Ref_Reg.setMaximum(100000000.0)
        self.doubleSpinBox_CSF_Ref_Reg.setObjectName("doubleSpinBox_CSF_Ref_Reg")
        self.gridLayout_3.addWidget(self.doubleSpinBox_CSF_Ref_Reg, 6, 1, 1, 1)
        self.label_Rel_Div_Current = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        self.label_Rel_Div_Current.setFont(font)
        self.label_Rel_Div_Current.setObjectName("label_Rel_Div_Current")
        self.gridLayout_3.addWidget(self.label_Rel_Div_Current, 8, 0, 1, 1)
        self.widget_No_Of_Refinement_Frequencies = QtWidgets.QWidget(self.widget)
        self.widget_No_Of_Refinement_Frequencies.setObjectName("widget_No_Of_Refinement_Frequencies")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_No_Of_Refinement_Frequencies)
        self.verticalLayout_5.setContentsMargins(23, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_No_Of_Refinement_Frequencies = QtWidgets.QLabel(self.widget_No_Of_Refinement_Frequencies)
        font = QtGui.QFont()
        self.label_No_Of_Refinement_Frequencies.setFont(font)
        self.label_No_Of_Refinement_Frequencies.setIndent(30)
        self.label_No_Of_Refinement_Frequencies.setObjectName("label_No_Of_Refinement_Frequencies")
        self.verticalLayout_5.addWidget(self.label_No_Of_Refinement_Frequencies)
        self.gridLayout_3.addWidget(self.widget_No_Of_Refinement_Frequencies, 3, 0, 1, 1)
        self.widget_Refinement_Frequencies_2 = QtWidgets.QWidget(self.widget)
        self.widget_Refinement_Frequencies_2.setObjectName("widget_Refinement_Frequencies_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_Refinement_Frequencies_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_Refinement_Frequency = QtWidgets.QLineEdit(self.widget_Refinement_Frequencies_2)
        font = QtGui.QFont()
        self.lineEdit_Refinement_Frequency.setFont(font)
        self.lineEdit_Refinement_Frequency.setObjectName("lineEdit_Refinement_Frequency")
        self.verticalLayout_3.addWidget(self.lineEdit_Refinement_Frequency)
        self.gridLayout_3.addWidget(self.widget_Refinement_Frequencies_2, 2, 1, 1, 1)
        self.label_CSF_Ref_Reg = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        self.label_CSF_Ref_Reg.setFont(font)
        self.label_CSF_Ref_Reg.setObjectName("label_CSF_Ref_Reg")
        self.gridLayout_3.addWidget(self.label_CSF_Ref_Reg, 6, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 7, 2, 1, 1)
        self.label_Min_Scaling = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        self.label_Min_Scaling.setFont(font)
        self.label_Min_Scaling.setObjectName("label_Min_Scaling")
        self.gridLayout_3.addWidget(self.label_Min_Scaling, 5, 0, 1, 1)
        self.pushButton_Deviation_Threshold = QtWidgets.QPushButton(self.widget)
        self.pushButton_Deviation_Threshold.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Deviation_Threshold.setIcon(icon)
        self.pushButton_Deviation_Threshold.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Deviation_Threshold.setFlat(True)
        self.pushButton_Deviation_Threshold.setObjectName("pushButton_Deviation_Threshold")
        self.gridLayout_3.addWidget(self.pushButton_Deviation_Threshold, 4, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 8, 2, 1, 1)
        self.doubleSpinBox_Rel_Div = QtWidgets.QDoubleSpinBox(self.widget)
        font = QtGui.QFont()
        self.doubleSpinBox_Rel_Div.setFont(font)
        self.doubleSpinBox_Rel_Div.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.doubleSpinBox_Rel_Div.setDecimals(4)
        self.doubleSpinBox_Rel_Div.setMinimum(0.0)
        self.doubleSpinBox_Rel_Div.setMaximum(10000000000.0)
        self.doubleSpinBox_Rel_Div.setProperty("value", 10.0)
        self.doubleSpinBox_Rel_Div.setObjectName("doubleSpinBox_Rel_Div")
        self.gridLayout_3.addWidget(self.doubleSpinBox_Rel_Div, 7, 1, 1, 1)
        self.label_Refinement_Frequencies = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        self.label_Refinement_Frequencies.setFont(font)
        self.label_Refinement_Frequencies.setObjectName("label_Refinement_Frequencies")
        self.gridLayout_3.addWidget(self.label_Refinement_Frequencies, 0, 0, 1, 1)
        self.pushButton_Min_Scaling = QtWidgets.QPushButton(self.widget)
        self.pushButton_Min_Scaling.setText("")
        self.pushButton_Min_Scaling.setIcon(icon)
        self.pushButton_Min_Scaling.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Min_Scaling.setFlat(True)
        self.pushButton_Min_Scaling.setObjectName("pushButton_Min_Scaling")
        self.gridLayout_3.addWidget(self.pushButton_Min_Scaling, 5, 3, 1, 1)
        self.comboBox_Refinement_Frequencies = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        self.comboBox_Refinement_Frequencies.setFont(font)
        self.comboBox_Refinement_Frequencies.setObjectName("comboBox_Refinement_Frequencies")
        self.comboBox_Refinement_Frequencies.addItem("")
        self.comboBox_Refinement_Frequencies.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_Refinement_Frequencies, 0, 1, 1, 1)
        self.widget_Refinement_Frequencies_3 = QtWidgets.QWidget(self.widget)
        self.widget_Refinement_Frequencies_3.setObjectName("widget_Refinement_Frequencies_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_Refinement_Frequencies_3)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_Refinement_Frequency = QtWidgets.QPushButton(self.widget_Refinement_Frequencies_3)
        self.pushButton_Refinement_Frequency.setText("")
        self.pushButton_Refinement_Frequency.setIcon(icon)
        self.pushButton_Refinement_Frequency.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Refinement_Frequency.setFlat(True)
        self.pushButton_Refinement_Frequency.setObjectName("pushButton_Refinement_Frequency")
        self.verticalLayout_7.addWidget(self.pushButton_Refinement_Frequency)
        self.gridLayout_3.addWidget(self.widget_Refinement_Frequencies_3, 2, 3, 1, 1)
        self.label_Rel_Div = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        self.label_Rel_Div.setFont(font)
        self.label_Rel_Div.setObjectName("label_Rel_Div")
        self.gridLayout_3.addWidget(self.label_Rel_Div, 7, 0, 1, 1)
        self.widget_No_Of_Refinement_Frequencies_3 = QtWidgets.QWidget(self.widget)
        self.widget_No_Of_Refinement_Frequencies_3.setObjectName("widget_No_Of_Refinement_Frequencies_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_No_Of_Refinement_Frequencies_3)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pushButton_No_of_Refinement_Frequencies = QtWidgets.QPushButton(self.widget_No_Of_Refinement_Frequencies_3)
        self.pushButton_No_of_Refinement_Frequencies.setText("")
        self.pushButton_No_of_Refinement_Frequencies.setIcon(icon)
        self.pushButton_No_of_Refinement_Frequencies.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_No_of_Refinement_Frequencies.setFlat(True)
        self.pushButton_No_of_Refinement_Frequencies.setObjectName("pushButton_No_of_Refinement_Frequencies")
        self.verticalLayout_9.addWidget(self.pushButton_No_of_Refinement_Frequencies)
        self.gridLayout_3.addWidget(self.widget_No_Of_Refinement_Frequencies_3, 3, 3, 1, 1)
        self.widget_No_Of_Refinement_Frequencies_2 = QtWidgets.QWidget(self.widget)
        self.widget_No_Of_Refinement_Frequencies_2.setObjectName("widget_No_Of_Refinement_Frequencies_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_No_Of_Refinement_Frequencies_2)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.spinBox_No_Of_Refinement_Frequencies = QtWidgets.QSpinBox(self.widget_No_Of_Refinement_Frequencies_2)
        font = QtGui.QFont()
        self.spinBox_No_Of_Refinement_Frequencies.setFont(font)
        self.spinBox_No_Of_Refinement_Frequencies.setMinimum(1)
        self.spinBox_No_Of_Refinement_Frequencies.setObjectName("spinBox_No_Of_Refinement_Frequencies")
        self.verticalLayout_8.addWidget(self.spinBox_No_Of_Refinement_Frequencies)
        self.gridLayout_3.addWidget(self.widget_No_Of_Refinement_Frequencies_2, 3, 1, 1, 1)
        self.doubleSpinBox_Min_Scaling = QtWidgets.QDoubleSpinBox(self.widget)
        font = QtGui.QFont()
        self.doubleSpinBox_Min_Scaling.setFont(font)
        self.doubleSpinBox_Min_Scaling.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.doubleSpinBox_Min_Scaling.setDecimals(1)
        self.doubleSpinBox_Min_Scaling.setMinimum(0.1)
        self.doubleSpinBox_Min_Scaling.setMaximum(1e+21)
        self.doubleSpinBox_Min_Scaling.setSingleStep(0.1)
        self.doubleSpinBox_Min_Scaling.setProperty("value", 1.0)
        self.doubleSpinBox_Min_Scaling.setObjectName("doubleSpinBox_Min_Scaling")
        self.gridLayout_3.addWidget(self.doubleSpinBox_Min_Scaling, 5, 1, 1, 1)
        self.label_Deviation_Threshold = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        self.label_Deviation_Threshold.setFont(font)
        self.label_Deviation_Threshold.setObjectName("label_Deviation_Threshold")
        self.gridLayout_3.addWidget(self.label_Deviation_Threshold, 4, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 6, 2, 1, 1)
        self.widget_Refinement_Frequencies_4 = QtWidgets.QWidget(self.widget)
        self.widget_Refinement_Frequencies_4.setObjectName("widget_Refinement_Frequencies_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_Refinement_Frequencies_4)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_Refinement_Frequency_2 = QtWidgets.QLabel(self.widget_Refinement_Frequencies_4)
        font = QtGui.QFont()
        self.label_Refinement_Frequency_2.setFont(font)
        self.label_Refinement_Frequency_2.setObjectName("label_Refinement_Frequency_2")
        self.gridLayout_2.addWidget(self.label_Refinement_Frequency_2, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_Refinement_Frequencies_4, 2, 2, 1, 1)
        self.pushButton_CSF_Ref_Reg = QtWidgets.QPushButton(self.widget)
        self.pushButton_CSF_Ref_Reg.setText("")
        self.pushButton_CSF_Ref_Reg.setIcon(icon)
        self.pushButton_CSF_Ref_Reg.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_CSF_Ref_Reg.setFlat(True)
        self.pushButton_CSF_Ref_Reg.setObjectName("pushButton_CSF_Ref_Reg")
        self.gridLayout_3.addWidget(self.pushButton_CSF_Ref_Reg, 6, 3, 1, 1)
        self.pushButton_Rel_Div = QtWidgets.QPushButton(self.widget)
        self.pushButton_Rel_Div.setText("")
        self.pushButton_Rel_Div.setIcon(icon)
        self.pushButton_Rel_Div.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Rel_Div.setFlat(True)
        self.pushButton_Rel_Div.setObjectName("pushButton_Rel_Div")
        self.gridLayout_3.addWidget(self.pushButton_Rel_Div, 7, 3, 1, 1)
        self.pushButton_Z_Length = QtWidgets.QPushButton(self.widget)
        self.pushButton_Z_Length.setText("")
        self.pushButton_Z_Length.setIcon(icon)
        self.pushButton_Z_Length.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Z_Length.setFlat(True)
        self.pushButton_Z_Length.setObjectName("pushButton_Z_Length")
        self.gridLayout_3.addWidget(self.pushButton_Z_Length, 8, 3, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 2)

        self.retranslateUi(centralwidget)
        QtCore.QMetaObject.connectSlotsByName(centralwidget)

    def retranslateUi(self, centralwidget):
        _translate = QtCore.QCoreApplication.translate
        centralwidget.setWindowTitle(_translate("centralwidget", "Mesh Refinement"))
        self.pushButton_Save.setText(_translate("centralwidget", "Ok"))
        self.pushButton_Cancel.setText(_translate("centralwidget", "Cancel"))
        self.label_Refinement_Frequency.setText(_translate("centralwidget", "Refinement Frequencies"))
        self.label_Deviation_Threshold_2.setText(_translate("centralwidget", "%"))
        self.label_Rel_Div_Current.setText(_translate("centralwidget", "Rel. Deviation of Current Magnitude"))
        self.label_No_Of_Refinement_Frequencies.setText(_translate("centralwidget", "Number of Refinement Frequencies"))
        self.lineEdit_Refinement_Frequency.setPlaceholderText(_translate("centralwidget", "[-1]"))
        self.label_CSF_Ref_Reg.setText(_translate("centralwidget", "CSF Refinement Area"))
        self.label_18.setText(_translate("centralwidget", "%"))
        self.label_Min_Scaling.setText(_translate("centralwidget", "Maximum Element to Voxel Ratio"))
        self.pushButton_Deviation_Threshold.setToolTip(_translate("centralwidget", "<html><head/><body><p><span style=\" font-family:\'wf_segoe-ui_normal,Segoe UI,Segoe WP,Tahoma,Arial,sans-serif,serif,EmojiFont\'; font-size:14pt; color:#212121; background-color:#ffffff;\">Provide threshold for acceptable electric potential deviation on neuron compartments as a percent of the overall voltage drop in the system. For example, if the parameters is set to 2% in the system with 0V/1V/2V/-3V on contacts, the threshold will be set to 0.1V.</span></p><p><span style=\" font-family:\'wf_segoe-ui_normal,Segoe UI,Segoe WP,Tahoma,Arial,sans-serif,serif,EmojiFont\'; font-size:14pt; font-weight:600; color:#212121; background-color:#ffffff;\">Important:</span><span style=\" font-family:\'wf_segoe-ui_normal,Segoe UI,Segoe WP,Tahoma,Arial,sans-serif,serif,EmojiFont\'; font-size:14pt; color:#212121; background-color:#ffffff;\"> For current-controlled mode, the threshold will be estimated after scaling the voltage on contacts to match the desired current. Therefore, the threshold will differ among the refinement frequencies due to changes in the impedance.</span></p></body></html>"))
        self.label_6.setText(_translate("centralwidget", "<html><head/><body><p><span style=\" font-style:italic;\">%</span></p></body></html>"))
        self.label_Refinement_Frequencies.setText(_translate("centralwidget", "Pick of Refinement Frequencies"))
        self.pushButton_Min_Scaling.setToolTip(_translate("centralwidget", "<html><head/><body><p><span style=\" font-size:14pt;\">Choose maximum ratio of FEM element edge to voxel size edge in the full CSF refinement (the ratio will be applied to elements containing CSF). We recommend to put it to 1.</span></p></body></html>"))
        self.comboBox_Refinement_Frequencies.setItemText(0, _translate("centralwidget", "Refinement Frequencies"))
        self.comboBox_Refinement_Frequencies.setItemText(1, _translate("centralwidget", "No. of Refinement Frequencies"))
        self.pushButton_Refinement_Frequency.setToolTip(_translate("centralwidget", "<html><head/><body><p><span style=\" font-size:14pt;\">Provide frequencies of sine wave signals for adaptive mesh refinement, e.g. [130.0,10000.0]. We recommend to make a choice basing on the frequency spectrum of the DBS signal or to use option No. of Refinement Frequencies instead.</span></p></body></html>"))
        self.label_Rel_Div.setText(_translate("centralwidget", "Rel. Deviation of E-field for Adaptive Refinement"))
        self.pushButton_No_of_Refinement_Frequencies.setToolTip(_translate("centralwidget", "<html><head/><body><p><span style=\" font-family:\'wf_segoe-ui_normal,Segoe UI,Segoe WP,Tahoma,Arial,sans-serif,serif,EmojiFont\'; font-size:14pt; color:#212121; background-color:#ffffff;\">Provide number of frequencies for mesh refinement. The frequencies will be defined by splitting power spectrum of the stimulation signal. </span><span style=\" font-family:\'wf_segoe-ui_normal,Segoe UI,Segoe WP,Tahoma,Arial,sans-serif,serif,EmojiFont\'; font-size:14pt; font-weight:600; color:#212121; background-color:#ffffff;\">Note:</span><span style=\" font-family:\'wf_segoe-ui_normal,Segoe UI,Segoe WP,Tahoma,Arial,sans-serif,serif,EmojiFont\'; font-size:14pt; color:#212121; background-color:#ffffff;\"> This parameter is an alternative to Refinement Frequency.</span></p></body></html>"))
        self.label_Deviation_Threshold.setText(_translate("centralwidget", "Deviation Threshold in Relation to Voltage"))
        self.label_27.setText(_translate("centralwidget", "mm"))
        self.label_Refinement_Frequency_2.setText(_translate("centralwidget", "Hz"))
        self.pushButton_CSF_Ref_Reg.setToolTip(_translate("centralwidget", "<html><head/><body><p><span style=\" font-size:14pt;\">This parameter defines area for full CSF refinement. FEM Elements with CSF will be refined in the region of interest (where neuron array is confined) + indent defined by CSF Refinement Area.</span></p></body></html>"))
        self.pushButton_Rel_Div.setToolTip(_translate("centralwidget", "<html><head/><body><p><span style=\" font-family:\'wf_segoe-ui_normal,Segoe UI,Segoe WP,Tahoma,Arial,sans-serif,serif,EmojiFont\'; font-size:14pt; color:#212121; background-color:#ffffff;\">Provide threshold for relative deviation of E-field during adaptive refinement.  A cell will be marked for refinement if the deviation on its midpoint is above the threshold. Cells with negligibly small E-fields are disregarded.</span></p></body></html>"))
        self.pushButton_Z_Length.setToolTip(_translate("centralwidget", "<html><head/><body><p><span style=\" font-size:14pt;\">Provide threshold for relative deviation of current on the contacts during adaptive mesh refinement. For multicontact current-controlled stimulation, a quasi impedance (an analogue to initially computed currents) is estimated instead.</span></p></body></html>"))

import icons_rc
import imgs_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    centralwidget = QtWidgets.QWidget()
    ui = Ui_centralwidget()
    ui.setupUi(centralwidget)
    centralwidget.show()
    sys.exit(app.exec_())

