# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pop_up_ui/pop_up_Full_Field_IFFT.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_centralwidget(object):
    def setupUi(self, centralwidget):
        centralwidget.setObjectName("centralwidget")
        centralwidget.resize(476, 275)
        centralwidget.setMaximumSize(QtCore.QSize(476, 275))
        centralwidget.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_Run_Close = QtWidgets.QWidget(centralwidget)
        font = QtGui.QFont()
        self.widget_Run_Close.setFont(font)
        self.widget_Run_Close.setObjectName("widget_Run_Close")
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout(self.widget_Run_Close)
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_57.addItem(spacerItem)
        self.pushButton_Save = QtWidgets.QPushButton(self.widget_Run_Close)
        font = QtGui.QFont()
        self.pushButton_Save.setFont(font)
        self.pushButton_Save.setStyleSheet("")
        self.pushButton_Save.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.horizontalLayout_57.addWidget(self.pushButton_Save)
        self.pushButton_Cancel = QtWidgets.QPushButton(self.widget_Run_Close)
        font = QtGui.QFont()
        self.pushButton_Cancel.setFont(font)
        self.pushButton_Cancel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_Cancel.setStyleSheet("")
        self.pushButton_Cancel.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.horizontalLayout_57.addWidget(self.pushButton_Cancel)
        self.gridLayout.addWidget(self.widget_Run_Close, 3, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 549, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_T_Step_End = QtWidgets.QLabel(centralwidget)
        font = QtGui.QFont()
        self.label_T_Step_End.setFont(font)
        self.label_T_Step_End.setObjectName("label_T_Step_End")
        self.gridLayout_4.addWidget(self.label_T_Step_End, 0, 0, 1, 1)
        self.checkBox_VTA_From_DivE = QtWidgets.QCheckBox(centralwidget)
        font = QtGui.QFont()
        self.checkBox_VTA_From_DivE.setFont(font)
        self.checkBox_VTA_From_DivE.setText("")
        self.checkBox_VTA_From_DivE.setObjectName("checkBox_VTA_From_DivE")
        self.gridLayout_4.addWidget(self.checkBox_VTA_From_DivE, 2, 1, 1, 1)
        self.checkBox_VTA_From_E = QtWidgets.QCheckBox(centralwidget)
        font = QtGui.QFont()
        self.checkBox_VTA_From_E.setFont(font)
        self.checkBox_VTA_From_E.setText("")
        self.checkBox_VTA_From_E.setObjectName("checkBox_VTA_From_E")
        self.gridLayout_4.addWidget(self.checkBox_VTA_From_E, 3, 1, 1, 1)
        self.pushButton_VT_From_DivE_2 = QtWidgets.QPushButton(centralwidget)
        self.pushButton_VT_From_DivE_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_VT_From_DivE_2.setIcon(icon)
        self.pushButton_VT_From_DivE_2.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_VT_From_DivE_2.setFlat(True)
        self.pushButton_VT_From_DivE_2.setObjectName("pushButton_VT_From_DivE_2")
        self.gridLayout_4.addWidget(self.pushButton_VT_From_DivE_2, 2, 2, 1, 1)
        self.pushButton_VTA_From_NEURON = QtWidgets.QPushButton(centralwidget)
        self.pushButton_VTA_From_NEURON.setText("")
        self.pushButton_VTA_From_NEURON.setIcon(icon)
        self.pushButton_VTA_From_NEURON.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_VTA_From_NEURON.setFlat(True)
        self.pushButton_VTA_From_NEURON.setObjectName("pushButton_VTA_From_NEURON")
        self.gridLayout_4.addWidget(self.pushButton_VTA_From_NEURON, 1, 2, 1, 1)
        self.pushButton_T_Step_End = QtWidgets.QPushButton(centralwidget)
        self.pushButton_T_Step_End.setText("")
        self.pushButton_T_Step_End.setIcon(icon)
        self.pushButton_T_Step_End.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_T_Step_End.setFlat(True)
        self.pushButton_T_Step_End.setObjectName("pushButton_T_Step_End")
        self.gridLayout_4.addWidget(self.pushButton_T_Step_End, 0, 2, 1, 1)
        self.checkBox_VTA_From_NEURON = QtWidgets.QCheckBox(centralwidget)
        font = QtGui.QFont()
        self.checkBox_VTA_From_NEURON.setFont(font)
        self.checkBox_VTA_From_NEURON.setText("")
        self.checkBox_VTA_From_NEURON.setObjectName("checkBox_VTA_From_NEURON")
        self.gridLayout_4.addWidget(self.checkBox_VTA_From_NEURON, 1, 1, 1, 1)
        self.pushButton_VTA_From_E = QtWidgets.QPushButton(centralwidget)
        self.pushButton_VTA_From_E.setText("")
        self.pushButton_VTA_From_E.setIcon(icon)
        self.pushButton_VTA_From_E.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_VTA_From_E.setFlat(True)
        self.pushButton_VTA_From_E.setObjectName("pushButton_VTA_From_E")
        self.gridLayout_4.addWidget(self.pushButton_VTA_From_E, 3, 2, 1, 1)
        self.spinBox_T_Step_End = QtWidgets.QSpinBox(centralwidget)
        font = QtGui.QFont()
        self.spinBox_T_Step_End.setFont(font)
        self.spinBox_T_Step_End.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBox_T_Step_End.setMaximum(1000000000)
        self.spinBox_T_Step_End.setProperty("value", 1200)
        self.spinBox_T_Step_End.setObjectName("spinBox_T_Step_End")
        self.gridLayout_4.addWidget(self.spinBox_T_Step_End, 0, 1, 1, 1)
        self.label_VTA_From_E = QtWidgets.QLabel(centralwidget)
        font = QtGui.QFont()
        self.label_VTA_From_E.setFont(font)
        self.label_VTA_From_E.setObjectName("label_VTA_From_E")
        self.gridLayout_4.addWidget(self.label_VTA_From_E, 3, 0, 1, 1)
        self.label_VTA_From_DivE = QtWidgets.QLabel(centralwidget)
        font = QtGui.QFont()
        self.label_VTA_From_DivE.setFont(font)
        self.label_VTA_From_DivE.setObjectName("label_VTA_From_DivE")
        self.gridLayout_4.addWidget(self.label_VTA_From_DivE, 2, 0, 1, 1)
        self.label_VTA_From_NEURON = QtWidgets.QLabel(centralwidget)
        font = QtGui.QFont()
        self.label_VTA_From_NEURON.setFont(font)
        self.label_VTA_From_NEURON.setObjectName("label_VTA_From_NEURON")
        self.gridLayout_4.addWidget(self.label_VTA_From_NEURON, 1, 0, 1, 1)
        self.widget_Activation_Threshold_1 = QtWidgets.QWidget(centralwidget)
        self.widget_Activation_Threshold_1.setObjectName("widget_Activation_Threshold_1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_Activation_Threshold_1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_Activation_Threshold = QtWidgets.QLabel(self.widget_Activation_Threshold_1)
        font = QtGui.QFont()
        self.label_Activation_Threshold.setFont(font)
        self.label_Activation_Threshold.setObjectName("label_Activation_Threshold")
        self.verticalLayout_5.addWidget(self.label_Activation_Threshold)
        self.gridLayout_4.addWidget(self.widget_Activation_Threshold_1, 4, 0, 1, 1)
        self.widget_Activation_Threshold_2 = QtWidgets.QWidget(centralwidget)
        self.widget_Activation_Threshold_2.setObjectName("widget_Activation_Threshold_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_Activation_Threshold_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit_Activation_Threshold = QtWidgets.QLineEdit(self.widget_Activation_Threshold_2)
        font = QtGui.QFont()
        self.lineEdit_Activation_Threshold.setFont(font)
        self.lineEdit_Activation_Threshold.setObjectName("lineEdit_Activation_Threshold")
        self.verticalLayout_6.addWidget(self.lineEdit_Activation_Threshold)
        self.gridLayout_4.addWidget(self.widget_Activation_Threshold_2, 4, 1, 1, 1)
        self.widget_Activation_Threshold_3 = QtWidgets.QWidget(centralwidget)
        self.widget_Activation_Threshold_3.setObjectName("widget_Activation_Threshold_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_Activation_Threshold_3)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_Truncate_The_Obtained_Full_Solution_2 = QtWidgets.QPushButton(self.widget_Activation_Threshold_3)
        self.pushButton_Truncate_The_Obtained_Full_Solution_2.setText("")
        self.pushButton_Truncate_The_Obtained_Full_Solution_2.setIcon(icon)
        self.pushButton_Truncate_The_Obtained_Full_Solution_2.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Truncate_The_Obtained_Full_Solution_2.setFlat(True)
        self.pushButton_Truncate_The_Obtained_Full_Solution_2.setObjectName("pushButton_Truncate_The_Obtained_Full_Solution_2")
        self.verticalLayout_7.addWidget(self.pushButton_Truncate_The_Obtained_Full_Solution_2)
        self.gridLayout_4.addWidget(self.widget_Activation_Threshold_3, 4, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)

        self.retranslateUi(centralwidget)
        QtCore.QMetaObject.connectSlotsByName(centralwidget)

    def retranslateUi(self, centralwidget):
        _translate = QtCore.QCoreApplication.translate
        centralwidget.setWindowTitle(_translate("centralwidget", "VTA approximation"))
        self.pushButton_Save.setText(_translate("centralwidget", "Ok"))
        self.pushButton_Cancel.setText(_translate("centralwidget", "Cancel"))
        self.label_T_Step_End.setText(_translate("centralwidget", "Time Steps Until"))
        self.label_VTA_From_E.setText(_translate("centralwidget", "VTA from E"))
        self.label_VTA_From_DivE.setText(_translate("centralwidget", "VTA from div(E)"))
        self.label_VTA_From_NEURON.setText(_translate("centralwidget", "Activation with NEURON"))
        self.label_Activation_Threshold.setText(_translate("centralwidget", "Activation threshold"))
        self.lineEdit_Activation_Threshold.setPlaceholderText(_translate("centralwidget", "0.0"))

import icons_rc
import imgs_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    centralwidget = QtWidgets.QWidget()
    ui = Ui_centralwidget()
    ui.setupUi(centralwidget)
    centralwidget.show()
    sys.exit(app.exec_())

