# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pop_up_ui/pop_up_External_Neuron_Array.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_centralwidget(object):
    def setupUi(self, centralwidget):
        centralwidget.setObjectName("centralwidget")
        centralwidget.resize(591, 1094)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(centralwidget.sizePolicy().hasHeightForWidth())
        centralwidget.setSizePolicy(sizePolicy)
        centralwidget.setMaximumSize(QtCore.QSize(591, 16777215))
        centralwidget.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_8 = QtWidgets.QWidget(self.frame)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_Global_Rot = QtWidgets.QLabel(self.widget_8)
        font = QtGui.QFont()
        self.label_Global_Rot.setFont(font)
        self.label_Global_Rot.setObjectName("label_Global_Rot")
        self.verticalLayout_10.addWidget(self.label_Global_Rot)
        self.horizontalLayout_5.addWidget(self.widget_8)
        self.widget_9 = QtWidgets.QWidget(self.frame)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.checkBox_Global_Rot = QtWidgets.QCheckBox(self.widget_9)
        font = QtGui.QFont()
        self.checkBox_Global_Rot.setFont(font)
        self.checkBox_Global_Rot.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_Global_Rot.setText("")
        self.checkBox_Global_Rot.setObjectName("checkBox_Global_Rot")
        self.verticalLayout_8.addWidget(self.checkBox_Global_Rot)
        self.horizontalLayout_5.addWidget(self.widget_9)
        self.widget_10 = QtWidgets.QWidget(self.frame)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.pushButton_Global_Rot = QtWidgets.QPushButton(self.widget_10)
        self.pushButton_Global_Rot.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_Global_Rot.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Global_Rot.setIcon(icon)
        self.pushButton_Global_Rot.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Global_Rot.setFlat(True)
        self.pushButton_Global_Rot.setObjectName("pushButton_Global_Rot")
        self.verticalLayout_11.addWidget(self.pushButton_Global_Rot)
        self.horizontalLayout_5.addWidget(self.widget_10)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_14.addLayout(self.horizontalLayout_5)
        self.widget_Global_Rot_Checked = QtWidgets.QWidget(self.frame)
        self.widget_Global_Rot_Checked.setObjectName("widget_Global_Rot_Checked")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_Global_Rot_Checked)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_Alpha_Array_Glob = QtWidgets.QPushButton(self.widget_Global_Rot_Checked)
        self.pushButton_Alpha_Array_Glob.setText("")
        self.pushButton_Alpha_Array_Glob.setIcon(icon)
        self.pushButton_Alpha_Array_Glob.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Alpha_Array_Glob.setFlat(True)
        self.pushButton_Alpha_Array_Glob.setObjectName("pushButton_Alpha_Array_Glob")
        self.gridLayout_2.addWidget(self.pushButton_Alpha_Array_Glob, 9, 3, 1, 1)
        self.doubleSpinBox_X_Step = QtWidgets.QDoubleSpinBox(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.doubleSpinBox_X_Step.setFont(font)
        self.doubleSpinBox_X_Step.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.doubleSpinBox_X_Step.setDecimals(4)
        self.doubleSpinBox_X_Step.setMinimum(-1e+47)
        self.doubleSpinBox_X_Step.setMaximum(1e+37)
        self.doubleSpinBox_X_Step.setProperty("value", 0.2)
        self.doubleSpinBox_X_Step.setObjectName("doubleSpinBox_X_Step")
        self.gridLayout_2.addWidget(self.doubleSpinBox_X_Step, 6, 1, 1, 1)
        self.pushButton_Y_Step = QtWidgets.QPushButton(self.widget_Global_Rot_Checked)
        self.pushButton_Y_Step.setText("")
        self.pushButton_Y_Step.setIcon(icon)
        self.pushButton_Y_Step.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Y_Step.setFlat(True)
        self.pushButton_Y_Step.setObjectName("pushButton_Y_Step")
        self.gridLayout_2.addWidget(self.pushButton_Y_Step, 7, 3, 1, 1)
        self.pushButton_Z_Steps = QtWidgets.QPushButton(self.widget_Global_Rot_Checked)
        self.pushButton_Z_Steps.setText("")
        self.pushButton_Z_Steps.setIcon(icon)
        self.pushButton_Z_Steps.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Z_Steps.setFlat(True)
        self.pushButton_Z_Steps.setObjectName("pushButton_Z_Steps")
        self.gridLayout_2.addWidget(self.pushButton_Z_Steps, 5, 3, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 1, 2, 1, 1)
        self.pushButton_X_Seed = QtWidgets.QPushButton(self.widget_Global_Rot_Checked)
        self.pushButton_X_Seed.setText("")
        self.pushButton_X_Seed.setIcon(icon)
        self.pushButton_X_Seed.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_X_Seed.setFlat(True)
        self.pushButton_X_Seed.setObjectName("pushButton_X_Seed")
        self.gridLayout_2.addWidget(self.pushButton_X_Seed, 0, 3, 1, 1)
        self.doubleSpinBox_X_Seed = QtWidgets.QDoubleSpinBox(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.doubleSpinBox_X_Seed.setFont(font)
        self.doubleSpinBox_X_Seed.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.doubleSpinBox_X_Seed.setDecimals(4)
        self.doubleSpinBox_X_Seed.setMinimum(-1e+56)
        self.doubleSpinBox_X_Seed.setMaximum(1e+47)
        self.doubleSpinBox_X_Seed.setProperty("value", 2.5781)
        self.doubleSpinBox_X_Seed.setObjectName("doubleSpinBox_X_Seed")
        self.gridLayout_2.addWidget(self.doubleSpinBox_X_Seed, 0, 1, 1, 1)
        self.label_Z_Step = QtWidgets.QLabel(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.label_Z_Step.setFont(font)
        self.label_Z_Step.setObjectName("label_Z_Step")
        self.gridLayout_2.addWidget(self.label_Z_Step, 8, 0, 1, 1)
        self.pushButton_Beta_Array_Glob = QtWidgets.QPushButton(self.widget_Global_Rot_Checked)
        self.pushButton_Beta_Array_Glob.setText("")
        self.pushButton_Beta_Array_Glob.setIcon(icon)
        self.pushButton_Beta_Array_Glob.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Beta_Array_Glob.setFlat(True)
        self.pushButton_Beta_Array_Glob.setObjectName("pushButton_Beta_Array_Glob")
        self.gridLayout_2.addWidget(self.pushButton_Beta_Array_Glob, 10, 3, 1, 1)
        self.doubleSpinBox_Y_Seed = QtWidgets.QDoubleSpinBox(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.doubleSpinBox_Y_Seed.setFont(font)
        self.doubleSpinBox_Y_Seed.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.doubleSpinBox_Y_Seed.setDecimals(4)
        self.doubleSpinBox_Y_Seed.setMinimum(-1e+42)
        self.doubleSpinBox_Y_Seed.setMaximum(1e+41)
        self.doubleSpinBox_Y_Seed.setProperty("value", -2.6821)
        self.doubleSpinBox_Y_Seed.setObjectName("doubleSpinBox_Y_Seed")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Y_Seed, 1, 1, 1, 1)
        self.label_X_Step = QtWidgets.QLabel(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.label_X_Step.setFont(font)
        self.label_X_Step.setObjectName("label_X_Step")
        self.gridLayout_2.addWidget(self.label_X_Step, 6, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout_2.addWidget(self.label_32, 7, 2, 1, 1)
        self.lineEdit_Gamma_Array_Glob = QtWidgets.QLineEdit(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.lineEdit_Gamma_Array_Glob.setFont(font)
        self.lineEdit_Gamma_Array_Glob.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.lineEdit_Gamma_Array_Glob.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEdit_Gamma_Array_Glob.setObjectName("lineEdit_Gamma_Array_Glob")
        self.gridLayout_2.addWidget(self.lineEdit_Gamma_Array_Glob, 11, 1, 1, 1)
        self.pushButton_Y_Seed = QtWidgets.QPushButton(self.widget_Global_Rot_Checked)
        self.pushButton_Y_Seed.setText("")
        self.pushButton_Y_Seed.setIcon(icon)
        self.pushButton_Y_Seed.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Y_Seed.setFlat(True)
        self.pushButton_Y_Seed.setObjectName("pushButton_Y_Seed")
        self.gridLayout_2.addWidget(self.pushButton_Y_Seed, 1, 3, 1, 1)
        self.doubleSpinBox_Z_Seed = QtWidgets.QDoubleSpinBox(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.doubleSpinBox_Z_Seed.setFont(font)
        self.doubleSpinBox_Z_Seed.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.doubleSpinBox_Z_Seed.setDecimals(4)
        self.doubleSpinBox_Z_Seed.setMinimum(-1e+47)
        self.doubleSpinBox_Z_Seed.setMaximum(1e+42)
        self.doubleSpinBox_Z_Seed.setProperty("value", -0.7)
        self.doubleSpinBox_Z_Seed.setObjectName("doubleSpinBox_Z_Seed")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Z_Seed, 2, 1, 1, 1)
        self.label_Z_Seed = QtWidgets.QLabel(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.label_Z_Seed.setFont(font)
        self.label_Z_Seed.setObjectName("label_Z_Seed")
        self.gridLayout_2.addWidget(self.label_Z_Seed, 2, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 9, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 0, 2, 1, 1)
        self.doubleSpinBox_Z_Step = QtWidgets.QDoubleSpinBox(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.doubleSpinBox_Z_Step.setFont(font)
        self.doubleSpinBox_Z_Step.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.doubleSpinBox_Z_Step.setDecimals(4)
        self.doubleSpinBox_Z_Step.setMinimum(-1e+46)
        self.doubleSpinBox_Z_Step.setMaximum(1e+42)
        self.doubleSpinBox_Z_Step.setProperty("value", 0.2)
        self.doubleSpinBox_Z_Step.setObjectName("doubleSpinBox_Z_Step")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Z_Step, 8, 1, 1, 1)
        self.label_Beta_Array_Glob = QtWidgets.QLabel(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.label_Beta_Array_Glob.setFont(font)
        self.label_Beta_Array_Glob.setObjectName("label_Beta_Array_Glob")
        self.gridLayout_2.addWidget(self.label_Beta_Array_Glob, 10, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 2, 2, 1, 1)
        self.lineEdit_Beta_Array_Glob = QtWidgets.QLineEdit(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.lineEdit_Beta_Array_Glob.setFont(font)
        self.lineEdit_Beta_Array_Glob.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.lineEdit_Beta_Array_Glob.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_Beta_Array_Glob.setObjectName("lineEdit_Beta_Array_Glob")
        self.gridLayout_2.addWidget(self.lineEdit_Beta_Array_Glob, 10, 1, 1, 1)
        self.spinBox_X_Steps = QtWidgets.QSpinBox(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.spinBox_X_Steps.setFont(font)
        self.spinBox_X_Steps.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBox_X_Steps.setMaximum(1000000000)
        self.spinBox_X_Steps.setProperty("value", 9)
        self.spinBox_X_Steps.setObjectName("spinBox_X_Steps")
        self.gridLayout_2.addWidget(self.spinBox_X_Steps, 3, 1, 1, 1)
        self.doubleSpinBox_Y_Step = QtWidgets.QDoubleSpinBox(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.doubleSpinBox_Y_Step.setFont(font)
        self.doubleSpinBox_Y_Step.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.doubleSpinBox_Y_Step.setDecimals(4)
        self.doubleSpinBox_Y_Step.setMinimum(-1e+36)
        self.doubleSpinBox_Y_Step.setMaximum(1e+41)
        self.doubleSpinBox_Y_Step.setProperty("value", 0.2)
        self.doubleSpinBox_Y_Step.setObjectName("doubleSpinBox_Y_Step")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Y_Step, 7, 1, 1, 1)
        self.pushButton_X_Step = QtWidgets.QPushButton(self.widget_Global_Rot_Checked)
        self.pushButton_X_Step.setText("")
        self.pushButton_X_Step.setIcon(icon)
        self.pushButton_X_Step.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_X_Step.setFlat(True)
        self.pushButton_X_Step.setObjectName("pushButton_X_Step")
        self.gridLayout_2.addWidget(self.pushButton_X_Step, 6, 3, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 11, 2, 1, 1)
        self.spinBox_Y_Steps = QtWidgets.QSpinBox(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.spinBox_Y_Steps.setFont(font)
        self.spinBox_Y_Steps.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBox_Y_Steps.setMaximum(1000000000)
        self.spinBox_Y_Steps.setObjectName("spinBox_Y_Steps")
        self.gridLayout_2.addWidget(self.spinBox_Y_Steps, 4, 1, 1, 1)
        self.pushButton_X_Steps = QtWidgets.QPushButton(self.widget_Global_Rot_Checked)
        self.pushButton_X_Steps.setText("")
        self.pushButton_X_Steps.setIcon(icon)
        self.pushButton_X_Steps.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_X_Steps.setFlat(True)
        self.pushButton_X_Steps.setObjectName("pushButton_X_Steps")
        self.gridLayout_2.addWidget(self.pushButton_X_Steps, 3, 3, 1, 1)
        self.label_Y_Seed = QtWidgets.QLabel(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.label_Y_Seed.setFont(font)
        self.label_Y_Seed.setObjectName("label_Y_Seed")
        self.gridLayout_2.addWidget(self.label_Y_Seed, 1, 0, 1, 1)
        self.pushButton_Z_Seed = QtWidgets.QPushButton(self.widget_Global_Rot_Checked)
        self.pushButton_Z_Seed.setText("")
        self.pushButton_Z_Seed.setIcon(icon)
        self.pushButton_Z_Seed.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Z_Seed.setFlat(True)
        self.pushButton_Z_Seed.setObjectName("pushButton_Z_Seed")
        self.gridLayout_2.addWidget(self.pushButton_Z_Seed, 2, 3, 1, 1)
        self.pushButton_Y_Steps = QtWidgets.QPushButton(self.widget_Global_Rot_Checked)
        self.pushButton_Y_Steps.setText("")
        self.pushButton_Y_Steps.setIcon(icon)
        self.pushButton_Y_Steps.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Y_Steps.setFlat(True)
        self.pushButton_Y_Steps.setObjectName("pushButton_Y_Steps")
        self.gridLayout_2.addWidget(self.pushButton_Y_Steps, 4, 3, 1, 1)
        self.spinBox_Z_Steps = QtWidgets.QSpinBox(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.spinBox_Z_Steps.setFont(font)
        self.spinBox_Z_Steps.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.spinBox_Z_Steps.setMaximum(1000000000)
        self.spinBox_Z_Steps.setProperty("value", 9)
        self.spinBox_Z_Steps.setObjectName("spinBox_Z_Steps")
        self.gridLayout_2.addWidget(self.spinBox_Z_Steps, 5, 1, 1, 1)
        self.label_X_Steps = QtWidgets.QLabel(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.label_X_Steps.setFont(font)
        self.label_X_Steps.setObjectName("label_X_Steps")
        self.gridLayout_2.addWidget(self.label_X_Steps, 3, 0, 1, 1)
        self.pushButton_Z_Step = QtWidgets.QPushButton(self.widget_Global_Rot_Checked)
        self.pushButton_Z_Step.setText("")
        self.pushButton_Z_Step.setIcon(icon)
        self.pushButton_Z_Step.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Z_Step.setFlat(True)
        self.pushButton_Z_Step.setObjectName("pushButton_Z_Step")
        self.gridLayout_2.addWidget(self.pushButton_Z_Step, 8, 3, 1, 1)
        self.label_Z_Steps = QtWidgets.QLabel(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.label_Z_Steps.setFont(font)
        self.label_Z_Steps.setObjectName("label_Z_Steps")
        self.gridLayout_2.addWidget(self.label_Z_Steps, 5, 0, 1, 1)
        self.label_Y_Steps = QtWidgets.QLabel(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.label_Y_Steps.setFont(font)
        self.label_Y_Steps.setObjectName("label_Y_Steps")
        self.gridLayout_2.addWidget(self.label_Y_Steps, 4, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout_2.addWidget(self.label_31, 6, 2, 1, 1)
        self.pushButton_Gamma_Array_Glob = QtWidgets.QPushButton(self.widget_Global_Rot_Checked)
        self.pushButton_Gamma_Array_Glob.setText("")
        self.pushButton_Gamma_Array_Glob.setIcon(icon)
        self.pushButton_Gamma_Array_Glob.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Gamma_Array_Glob.setFlat(True)
        self.pushButton_Gamma_Array_Glob.setObjectName("pushButton_Gamma_Array_Glob")
        self.gridLayout_2.addWidget(self.pushButton_Gamma_Array_Glob, 11, 3, 1, 1)
        self.label_Alpha_Array_Glob = QtWidgets.QLabel(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.label_Alpha_Array_Glob.setFont(font)
        self.label_Alpha_Array_Glob.setObjectName("label_Alpha_Array_Glob")
        self.gridLayout_2.addWidget(self.label_Alpha_Array_Glob, 9, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayout_2.addWidget(self.label_33, 8, 2, 1, 1)
        self.label_Gamma_Array_Glob = QtWidgets.QLabel(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.label_Gamma_Array_Glob.setFont(font)
        self.label_Gamma_Array_Glob.setObjectName("label_Gamma_Array_Glob")
        self.gridLayout_2.addWidget(self.label_Gamma_Array_Glob, 11, 0, 1, 1)
        self.label_Y_Step = QtWidgets.QLabel(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.label_Y_Step.setFont(font)
        self.label_Y_Step.setObjectName("label_Y_Step")
        self.gridLayout_2.addWidget(self.label_Y_Step, 7, 0, 1, 1)
        self.lineEdit_Alpha_Array_Glob = QtWidgets.QLineEdit(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.lineEdit_Alpha_Array_Glob.setFont(font)
        self.lineEdit_Alpha_Array_Glob.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.lineEdit_Alpha_Array_Glob.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEdit_Alpha_Array_Glob.setObjectName("lineEdit_Alpha_Array_Glob")
        self.gridLayout_2.addWidget(self.lineEdit_Alpha_Array_Glob, 9, 1, 1, 1)
        self.label_X_Seed = QtWidgets.QLabel(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.label_X_Seed.setFont(font)
        self.label_X_Seed.setObjectName("label_X_Seed")
        self.gridLayout_2.addWidget(self.label_X_Seed, 0, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.widget_Global_Rot_Checked)
        font = QtGui.QFont()
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 10, 2, 1, 1)
        self.verticalLayout_14.addWidget(self.widget_Global_Rot_Checked)
        self.widget_Global_Rot_Unchecked = QtWidgets.QWidget(self.frame)
        self.widget_Global_Rot_Unchecked.setObjectName("widget_Global_Rot_Unchecked")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_Global_Rot_Unchecked)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_26 = QtWidgets.QLabel(self.widget_Global_Rot_Unchecked)
        font = QtGui.QFont()
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 6, 2, 1, 1)
        self.pushButton_Y_Coordinate_Old = QtWidgets.QPushButton(self.widget_Global_Rot_Unchecked)
        self.pushButton_Y_Coordinate_Old.setText("")
        self.pushButton_Y_Coordinate_Old.setIcon(icon)
        self.pushButton_Y_Coordinate_Old.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Y_Coordinate_Old.setFlat(True)
        self.pushButton_Y_Coordinate_Old.setObjectName("pushButton_Y_Coordinate_Old")
        self.gridLayout_3.addWidget(self.pushButton_Y_Coordinate_Old, 1, 3, 1, 1)
        self.label_X_Coordinate_Old = QtWidgets.QLabel(self.widget_Global_Rot_Unchecked)
        font = QtGui.QFont()
        self.label_X_Coordinate_Old.setFont(font)
        self.label_X_Coordinate_Old.setObjectName("label_X_Coordinate_Old")
        self.gridLayout_3.addWidget(self.label_X_Coordinate_Old, 0, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.widget_Global_Rot_Unchecked)
        font = QtGui.QFont()
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 4, 2, 1, 1)
        self.label_ZX_Angles = QtWidgets.QLabel(self.widget_Global_Rot_Unchecked)
        font = QtGui.QFont()
        self.label_ZX_Angles.setFont(font)
        self.label_ZX_Angles.setObjectName("label_ZX_Angles")
        self.gridLayout_3.addWidget(self.label_ZX_Angles, 5, 0, 1, 1)
        self.lineEdit_YZ_Angles = QtWidgets.QLineEdit(self.widget_Global_Rot_Unchecked)
        font = QtGui.QFont()
        self.lineEdit_YZ_Angles.setFont(font)
        self.lineEdit_YZ_Angles.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.lineEdit_YZ_Angles.setObjectName("lineEdit_YZ_Angles")
        self.gridLayout_3.addWidget(self.lineEdit_YZ_Angles, 4, 1, 1, 1)
        self.lineEdit_XY_Angles = QtWidgets.QLineEdit(self.widget_Global_Rot_Unchecked)
        font = QtGui.QFont()
        self.lineEdit_XY_Angles.setFont(font)
        self.lineEdit_XY_Angles.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.lineEdit_XY_Angles.setObjectName("lineEdit_XY_Angles")
        self.gridLayout_3.addWidget(self.lineEdit_XY_Angles, 6, 1, 1, 1)
        self.pushButton_YZ_Angles = QtWidgets.QPushButton(self.widget_Global_Rot_Unchecked)
        self.pushButton_YZ_Angles.setText("")
        self.pushButton_YZ_Angles.setIcon(icon)
        self.pushButton_YZ_Angles.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_YZ_Angles.setFlat(True)
        self.pushButton_YZ_Angles.setObjectName("pushButton_YZ_Angles")
        self.gridLayout_3.addWidget(self.pushButton_YZ_Angles, 4, 3, 1, 1)
        self.lineEdit_Z_Coordinate_Old = QtWidgets.QLineEdit(self.widget_Global_Rot_Unchecked)
        font = QtGui.QFont()
        self.lineEdit_Z_Coordinate_Old.setFont(font)
        self.lineEdit_Z_Coordinate_Old.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.lineEdit_Z_Coordinate_Old.setObjectName("lineEdit_Z_Coordinate_Old")
        self.gridLayout_3.addWidget(self.lineEdit_Z_Coordinate_Old, 3, 1, 1, 1)
        self.pushButton_XY_Angles = QtWidgets.QPushButton(self.widget_Global_Rot_Unchecked)
        self.pushButton_XY_Angles.setText("")
        self.pushButton_XY_Angles.setIcon(icon)
        self.pushButton_XY_Angles.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_XY_Angles.setFlat(True)
        self.pushButton_XY_Angles.setObjectName("pushButton_XY_Angles")
        self.gridLayout_3.addWidget(self.pushButton_XY_Angles, 6, 3, 1, 1)
        self.label_Z_Coordinate_Old = QtWidgets.QLabel(self.widget_Global_Rot_Unchecked)
        font = QtGui.QFont()
        self.label_Z_Coordinate_Old.setFont(font)
        self.label_Z_Coordinate_Old.setObjectName("label_Z_Coordinate_Old")
        self.gridLayout_3.addWidget(self.label_Z_Coordinate_Old, 3, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.widget_Global_Rot_Unchecked)
        font = QtGui.QFont()
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.gridLayout_3.addWidget(self.label_34, 0, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.widget_Global_Rot_Unchecked)
        font = QtGui.QFont()
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.gridLayout_3.addWidget(self.label_36, 3, 2, 1, 1)
        self.pushButton_ZX_Angles = QtWidgets.QPushButton(self.widget_Global_Rot_Unchecked)
        self.pushButton_ZX_Angles.setText("")
        self.pushButton_ZX_Angles.setIcon(icon)
        self.pushButton_ZX_Angles.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_ZX_Angles.setFlat(True)
        self.pushButton_ZX_Angles.setObjectName("pushButton_ZX_Angles")
        self.gridLayout_3.addWidget(self.pushButton_ZX_Angles, 5, 3, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.widget_Global_Rot_Unchecked)
        font = QtGui.QFont()
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.gridLayout_3.addWidget(self.label_35, 1, 2, 1, 1)
        self.label_XY_Angles = QtWidgets.QLabel(self.widget_Global_Rot_Unchecked)
        font = QtGui.QFont()
        self.label_XY_Angles.setFont(font)
        self.label_XY_Angles.setObjectName("label_XY_Angles")
        self.gridLayout_3.addWidget(self.label_XY_Angles, 6, 0, 1, 1)
        self.label_Y_Coordinate_Old = QtWidgets.QLabel(self.widget_Global_Rot_Unchecked)
        font = QtGui.QFont()
        self.label_Y_Coordinate_Old.setFont(font)
        self.label_Y_Coordinate_Old.setObjectName("label_Y_Coordinate_Old")
        self.gridLayout_3.addWidget(self.label_Y_Coordinate_Old, 1, 0, 1, 1)
        self.lineEdit_Y_Coordinate_Old = QtWidgets.QLineEdit(self.widget_Global_Rot_Unchecked)
        font = QtGui.QFont()
        self.lineEdit_Y_Coordinate_Old.setFont(font)
        self.lineEdit_Y_Coordinate_Old.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.lineEdit_Y_Coordinate_Old.setObjectName("lineEdit_Y_Coordinate_Old")
        self.gridLayout_3.addWidget(self.lineEdit_Y_Coordinate_Old, 1, 1, 1, 1)
        self.lineEdit_ZX_Angles = QtWidgets.QLineEdit(self.widget_Global_Rot_Unchecked)
        font = QtGui.QFont()
        self.lineEdit_ZX_Angles.setFont(font)
        self.lineEdit_ZX_Angles.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.lineEdit_ZX_Angles.setObjectName("lineEdit_ZX_Angles")
        self.gridLayout_3.addWidget(self.lineEdit_ZX_Angles, 5, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.widget_Global_Rot_Unchecked)
        font = QtGui.QFont()
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 5, 2, 1, 1)
        self.lineEdit_X_Coordinate_Old = QtWidgets.QLineEdit(self.widget_Global_Rot_Unchecked)
        font = QtGui.QFont()
        self.lineEdit_X_Coordinate_Old.setFont(font)
        self.lineEdit_X_Coordinate_Old.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.lineEdit_X_Coordinate_Old.setObjectName("lineEdit_X_Coordinate_Old")
        self.gridLayout_3.addWidget(self.lineEdit_X_Coordinate_Old, 0, 1, 1, 1)
        self.label_YZ_Angles = QtWidgets.QLabel(self.widget_Global_Rot_Unchecked)
        font = QtGui.QFont()
        self.label_YZ_Angles.setFont(font)
        self.label_YZ_Angles.setObjectName("label_YZ_Angles")
        self.gridLayout_3.addWidget(self.label_YZ_Angles, 4, 0, 1, 1)
        self.pushButton_X_Coordinate_Old = QtWidgets.QPushButton(self.widget_Global_Rot_Unchecked)
        self.pushButton_X_Coordinate_Old.setText("")
        self.pushButton_X_Coordinate_Old.setIcon(icon)
        self.pushButton_X_Coordinate_Old.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_X_Coordinate_Old.setFlat(True)
        self.pushButton_X_Coordinate_Old.setObjectName("pushButton_X_Coordinate_Old")
        self.gridLayout_3.addWidget(self.pushButton_X_Coordinate_Old, 0, 3, 1, 1)
        self.pushButton_Z_Coordinate_Old = QtWidgets.QPushButton(self.widget_Global_Rot_Unchecked)
        self.pushButton_Z_Coordinate_Old.setText("")
        self.pushButton_Z_Coordinate_Old.setIcon(icon)
        self.pushButton_Z_Coordinate_Old.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Z_Coordinate_Old.setFlat(True)
        self.pushButton_Z_Coordinate_Old.setObjectName("pushButton_Z_Coordinate_Old")
        self.gridLayout_3.addWidget(self.pushButton_Z_Coordinate_Old, 3, 3, 1, 1)
        self.verticalLayout_14.addWidget(self.widget_Global_Rot_Unchecked)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem1)
        self.widget_Run_Close = QtWidgets.QWidget(self.frame)
        font = QtGui.QFont()
        self.widget_Run_Close.setFont(font)
        self.widget_Run_Close.setObjectName("widget_Run_Close")
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout(self.widget_Run_Close)
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_57.addItem(spacerItem2)
        self.pushButton_Save = QtWidgets.QPushButton(self.widget_Run_Close)
        font = QtGui.QFont()
        self.pushButton_Save.setFont(font)
        self.pushButton_Save.setStyleSheet("")
        self.pushButton_Save.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.horizontalLayout_57.addWidget(self.pushButton_Save)
        self.pushButton_Cancel = QtWidgets.QPushButton(self.widget_Run_Close)
        font = QtGui.QFont()
        self.pushButton_Cancel.setFont(font)
        self.pushButton_Cancel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_Cancel.setStyleSheet("")
        self.pushButton_Cancel.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.horizontalLayout_57.addWidget(self.pushButton_Cancel)
        self.verticalLayout_14.addWidget(self.widget_Run_Close)
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 1)

        self.retranslateUi(centralwidget)
        QtCore.QMetaObject.connectSlotsByName(centralwidget)

    def retranslateUi(self, centralwidget):
        _translate = QtCore.QCoreApplication.translate
        centralwidget.setWindowTitle(_translate("centralwidget", "External Neuron Array"))
        self.label_Global_Rot.setText(_translate("centralwidget", "Generate Ordered Neuron Array"))
        self.pushButton_Global_Rot.setToolTip(_translate("centralwidget", "<html><head/><body><p><span style=\" font-size:14pt;\">Check if an ordered neuron array to be generated, otherwise location of each neuron models should be provided manually. Ordered neuron array approach is suitable for VTA estimations. It will be defined by coordinates of the seeding point (central compartment of central neuron), number of neurons in one plane along one axis, distance between them and the rotation of the plane. By default, neurons (axons) are aligned along Y axis.</span></p><p><span style=\" font-size:14pt; font-weight:600;\">Note</span><span style=\" font-size:14pt;\">: In this case axonal compartments lie on one line.</span></p></body></html>"))
        self.pushButton_Alpha_Array_Glob.setToolTip(_translate("centralwidget", "<html><head/><body><p><span style=\" font-size:14pt;\">Provide rotational angles arond X axis for the plane with central neuron compartments.</span></p><p><span style=\" font-size:14pt; font-weight:600;\">Important</span><span style=\" font-size:14pt;\">: Each plane is defined by 3 rotational angles. For example, if we do not want to rotate the plane, we should provide 0.0 to each of \'Turn around .. axis\'. If we want to rotate plane along X axis by 45 degrees, we should procide 45.0 0.0 0.0. If we want to have both planes we should provide [0.0,45.0],[0.0,0.0],[0.0,0.0].</span></p></body></html>"))
        self.pushButton_Y_Step.setToolTip(_translate("centralwidget", "<html><head/><body><p><span style=\" font-size:14pt;\">Provide distance between neuron models along Y axis</span></p></body></html>"))
        self.pushButton_Z_Steps.setToolTip(_translate("centralwidget", "<html><head/><body><p><span style=\" font-size:14pt;\">Provide number of neuron models that will be additionally placed on the Z axis around the central neuron.</span></p></body></html>"))
        self.label_29.setText(_translate("centralwidget", "mm"))
        self.pushButton_X_Seed.setToolTip(_translate("centralwidget", "<html><head/><body><p><span style=\" font-size:14pt;\">Provide X coordinate of the seeding node (central compartment) of the central neuron in the MRI data space.</span></p></body></html>"))
        self.label_Z_Step.setText(_translate("centralwidget", "Z step"))
        self.pushButton_Beta_Array_Glob.setToolTip(_translate("centralwidget", "<html><head/><body><p><span style=\" font-size:14pt;\">Provide rotational angles arond Y axis for the plane with central neuron compartments.</span></p><p><span style=\" font-size:14pt; font-weight:600;\">Important</span><span style=\" font-size:14pt;\">: Each plane is defined by 3 rotational angles. For example, if we do not want to rotate the plane, we should provide 0.0 to each of \'Turn around .. axis\'. If we want to rotate plane along Y axis by 90 degrees, we should procide 0.0 90.0 0.0. If we want to have both planes we should provide [0.0,0.0],[0.0,90.0],[0.0,0.0].</span></p></body></html>"))
        self.label_X_Step.setText(_translate("centralwidget", "X step"))
        self.label_32.setText(_translate("centralwidget", "mm"))
        self.lineEdit_Gamma_Array_Glob.setToolTip(_translate("centralwidget", "Enter Vector: Format: [0.00, 0.00, 0.00]"))
        self.lineEdit_Gamma_Array_Glob.setPlaceholderText(_translate("centralwidget", "[0.00, 0.00, 0.00]"))
        self.pushButton_Y_Seed.setToolTip(_translate("centralwidget", "<html><head/><body><p><span style=\" font-size:14pt;\">Provide Y coordinate of the seeding node (central compartment)  of the central neuron in the MRI data space.</span></p></body></html>"))
        self.label_Z_Seed.setText(_translate("centralwidget", "Z seed"))
        self.label_21.setText(_translate("centralwidget", "<html><head/><body><p><span style=\" font-style:italic;\">deg</span></p></body></html>"))
        self.label_19.setText(_translate("centralwidget", "mm"))
        self.label_Beta_Array_Glob.setText(_translate("centralwidget", "Turn around Y axis"))
        self.label_30.setText(_translate("centralwidget", "mm"))
        self.lineEdit_Beta_Array_Glob.setToolTip(_translate("centralwidget", "Enter Vector: Format: [0.00, 0.00, 0.00]"))
        self.lineEdit_Beta_Array_Glob.setPlaceholderText(_translate("centralwidget", "[0.00, 0.00, 0.00]"))
        self.pushButton_X_Step.setToolTip(_translate("centralwidget", "<html><head/><body><p><span style=\" font-size:14pt;\">Provide distance between neuron models along X axis</span></p></body></html>"))
        self.label_23.setText(_translate("centralwidget", "<html><head/><body><p><span style=\" font-style:italic;\">deg</span></p></body></html>"))
        self.pushButton_X_Steps.setToolTip(_translate("centralwidget", "<html><head/><body><p><span style=\" font-size:14pt;\">Provide number of neuron models that will be additionally placed on the X axis around the central neuron.</span></p></body></html>"))
        self.label_Y_Seed.setText(_translate("centralwidget", "Y seed"))
        self.pushButton_Z_Seed.setToolTip(_translate("centralwidget", "<html><head/><body><p><span style=\" font-size:14pt;\">Provide Z coordinate of the seeding node (central compartment)  of the central neuron in the MRI data space.</span></p></body></html>"))
        self.pushButton_Y_Steps.setToolTip(_translate("centralwidget", "<html><head/><body><p><span style=\" font-size:14pt;\">Provide number of neuron models that will be additionally placed on the Y axis around the central neuron.</span></p></body></html>"))
        self.label_X_Steps.setText(_translate("centralwidget", "X steps"))
        self.pushButton_Z_Step.setToolTip(_translate("centralwidget", "<html><head/><body><p><span style=\" font-size:14pt;\">Provide distance between neuron models along Z axis</span></p></body></html>"))
        self.label_Z_Steps.setText(_translate("centralwidget", "Z steps"))
        self.label_Y_Steps.setText(_translate("centralwidget", "Y steps"))
        self.label_31.setText(_translate("centralwidget", "mm"))
        self.pushButton_Gamma_Array_Glob.setToolTip(_translate("centralwidget", "<html><head/><body><p><span style=\" font-size:14pt;\">Provide rotational angles arond Z axis for the plane with central neuron compartments.</span></p><p><span style=\" font-size:14pt; font-weight:600;\">Important</span><span style=\" font-size:14pt;\">: Each plane is defined by 3 rotational angles. For example, if we do not want to rotate the plane, we should provide 0.0 to each of \'Turn around .. axis\'. If we want to rotate plane along Z axis by 135 degrees, we should procide 0.0 0.0 135.0. If we want to have both planes we should provide [0.0,0.0],[0.0,0.0],[0.0,135.0].</span></p></body></html>"))
        self.label_Alpha_Array_Glob.setText(_translate("centralwidget", "Turn around X axis"))
        self.label_33.setText(_translate("centralwidget", "mm"))
        self.label_Gamma_Array_Glob.setText(_translate("centralwidget", "Turn around Z axis"))
        self.label_Y_Step.setText(_translate("centralwidget", "Y step"))
        self.lineEdit_Alpha_Array_Glob.setToolTip(_translate("centralwidget", "Enter Vector: Format: [0.00, 0.00, 0.00]"))
        self.lineEdit_Alpha_Array_Glob.setPlaceholderText(_translate("centralwidget", "[0.00, 0.00, 0.00]"))
        self.label_X_Seed.setText(_translate("centralwidget", "X seed"))
        self.label_22.setText(_translate("centralwidget", "<html><head/><body><p><span style=\" font-style:italic;\">deg</span></p></body></html>"))
        self.label_26.setText(_translate("centralwidget", "<html><head/><body><p><span style=\" font-style:italic;\">deg</span></p></body></html>"))
        self.pushButton_Y_Coordinate_Old.setToolTip(_translate("centralwidget", "<html><head/><body><p><span style=\" font-size:14pt;\">Provide Y coordinate of the seeding node (central compartment)  for each neuron in the MRI data space.</span></p></body></html>"))
        self.label_X_Coordinate_Old.setText(_translate("centralwidget", "X-coord of Central Node"))
        self.label_24.setText(_translate("centralwidget", "<html><head/><body><p><span style=\" font-style:italic;\">deg</span></p></body></html>"))
        self.label_ZX_Angles.setText(_translate("centralwidget", "Angles in Plane ZX"))
        self.lineEdit_YZ_Angles.setPlaceholderText(_translate("centralwidget", "[0.0, 0.0]"))
        self.lineEdit_XY_Angles.setPlaceholderText(_translate("centralwidget", "0.0, 0.0]"))
        self.pushButton_YZ_Angles.setToolTip(_translate("centralwidget", "<html><head/><body><p><span style=\" font-size:14pt;\">Provide rotational angles for neuron models arond local X axis (i.e. models will be rotated relatively to their own central compartments).</span></p><p><span style=\" font-size:14pt; font-weight:600;\">Important</span><span style=\" font-size:14pt;\">: Unlike \'Turn around .. axis\' parameter, here the angle vectors are not required to have the same legnth, as the models will be rotated using 3 nested &quot;for&quot; loops. For example, to have only models rotated by 90 degrees around X axis, we should provide 90.0 , 0.0 , 0.0. If we want to rotate them additionally around Y axis by 30 degrees, we should provide 90.0, [0.0,30.0], 0.0.</span></p></body></html>"))
        self.lineEdit_Z_Coordinate_Old.setToolTip(_translate("centralwidget", "Enter Co-ordinate: Format: [-0.5,-0.5,-0.5,...,0.5]"))
        self.lineEdit_Z_Coordinate_Old.setPlaceholderText(_translate("centralwidget", "[-0.5,-0.5,-0.5,...,0.5]"))
        self.pushButton_XY_Angles.setToolTip(_translate("centralwidget", "<html><head/><body><p><span style=\" font-size:14pt;\">Provide rotational angles for neuron models arond local Z axis (i.e. models will be rotated relatively to their own central compartments).</span></p><p><span style=\" font-size:14pt; font-weight:600;\">Important</span><span style=\" font-size:14pt;\">: Unlike \'Turn around .. axis\'., here the angle vectors are not required to have the same legnth, as the models will be rotated using 3 nested &quot;for&quot; loops. For example, to have only models rotated by 90 degrees around X axis, we should provide 90.0 , 0.0 , 0.0. If we want to rotate them additionally around Y axis by 30 degrees, we should provide 90.0, [0.0,30.0], 0.0.</span></p></body></html>"))
        self.label_Z_Coordinate_Old.setText(_translate("centralwidget", "Z-coord of Central Node"))
        self.label_34.setText(_translate("centralwidget", "mm"))
        self.label_36.setText(_translate("centralwidget", "mm"))
        self.pushButton_ZX_Angles.setToolTip(_translate("centralwidget", "<html><head/><body><p><span style=\" font-size:14pt;\">Provide rotational angles for neuron models arond local Y axis (i.e. models will be rotated relatively to their own central compartments).</span></p><p><span style=\" font-size:14pt; font-weight:600;\">Important</span><span style=\" font-size:14pt;\">: Unlike \'Turn around .. axis\'., here the angle vectors are not required to have the same legnth, as the models will be rotated using 3 nested &quot;for&quot; loops. For example, to have only models rotated by 90 degrees around X axis, we should provide 90.0 , 0.0 , 0.0. If we want to rotate them additionally around Y axis by 30 degrees, we should provide 90.0, [0.0,30.0], 0.0.</span></p></body></html>"))
        self.label_35.setText(_translate("centralwidget", "mm"))
        self.label_XY_Angles.setText(_translate("centralwidget", "Angles in Plane XY"))
        self.label_Y_Coordinate_Old.setText(_translate("centralwidget", "Y-coord of Central Node"))
        self.lineEdit_Y_Coordinate_Old.setToolTip(_translate("centralwidget", "Enter co-ordinate: Format: [-2.6281,-2.6281,-2.6281,...,-3.6281]"))
        self.lineEdit_Y_Coordinate_Old.setPlaceholderText(_translate("centralwidget", "[-2.6281,-2.6281,-2.6281,...,-3.6281]"))
        self.lineEdit_ZX_Angles.setPlaceholderText(_translate("centralwidget", "[0.0, 0.0]"))
        self.label_25.setText(_translate("centralwidget", "<html><head/><body><p><span style=\" font-style:italic;\">deg</span></p></body></html>"))
        self.lineEdit_X_Coordinate_Old.setToolTip(_translate("centralwidget", "Enter Co-ordinate: Format: [+2.5781,+1.5781,+3.5781,...,+3.5781]"))
        self.lineEdit_X_Coordinate_Old.setPlaceholderText(_translate("centralwidget", "[+2.5781,+1.5781,+3.5781,...,+3.5781]"))
        self.label_YZ_Angles.setText(_translate("centralwidget", "Angles in Plane YZ"))
        self.pushButton_X_Coordinate_Old.setToolTip(_translate("centralwidget", "<html><head/><body><p><span style=\" font-size:14pt;\">Provide X coordinate of the seeding node (central compartment)  for each neuron in the MRI data space.</span></p></body></html>"))
        self.pushButton_Z_Coordinate_Old.setToolTip(_translate("centralwidget", "<html><head/><body><p><span style=\" font-size:14pt;\">Provide Z coordinate of the seeding node (central compartment)  for each neuron in the MRI data space.</span></p></body></html>"))
        self.pushButton_Save.setText(_translate("centralwidget", "Ok"))
        self.pushButton_Cancel.setText(_translate("centralwidget", "Cancel"))

import icons_rc
import imgs_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    centralwidget = QtWidgets.QWidget()
    ui = Ui_centralwidget()
    ui.setupUi(centralwidget)
    centralwidget.show()
    sys.exit(app.exec_())

