# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pop_up_ui/pop_up_CPE_Active.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_centralwidget(object):
    def setupUi(self, centralwidget):
        centralwidget.setObjectName("centralwidget")
        centralwidget.resize(579, 260)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(centralwidget.sizePolicy().hasHeightForWidth())
        centralwidget.setSizePolicy(sizePolicy)
        centralwidget.setMaximumSize(QtCore.QSize(579, 260))
        centralwidget.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_Run_Close = QtWidgets.QWidget(centralwidget)
        font = QtGui.QFont()
        self.widget_Run_Close.setFont(font)
        self.widget_Run_Close.setObjectName("widget_Run_Close")
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout(self.widget_Run_Close)
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_57.addItem(spacerItem)
        self.pushButton_Save = QtWidgets.QPushButton(self.widget_Run_Close)
        font = QtGui.QFont()
        self.pushButton_Save.setFont(font)
        self.pushButton_Save.setStyleSheet("")
        self.pushButton_Save.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.horizontalLayout_57.addWidget(self.pushButton_Save)
        self.pushButton_Cancel = QtWidgets.QPushButton(self.widget_Run_Close)
        font = QtGui.QFont()
        self.pushButton_Cancel.setFont(font)
        self.pushButton_Cancel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_Cancel.setStyleSheet("")
        self.pushButton_Cancel.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.horizontalLayout_57.addWidget(self.pushButton_Cancel)
        self.gridLayout.addWidget(self.widget_Run_Close, 2, 1, 1, 1)
        self.widget = QtWidgets.QWidget(centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.doubleSpinBox_Alpha_Ground = QtWidgets.QDoubleSpinBox(self.widget)
        font = QtGui.QFont()
        self.doubleSpinBox_Alpha_Ground.setFont(font)
        self.doubleSpinBox_Alpha_Ground.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.doubleSpinBox_Alpha_Ground.setDecimals(4)
        self.doubleSpinBox_Alpha_Ground.setMinimum(-1e+44)
        self.doubleSpinBox_Alpha_Ground.setMaximum(1e+35)
        self.doubleSpinBox_Alpha_Ground.setObjectName("doubleSpinBox_Alpha_Ground")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Alpha_Ground, 2, 1, 1, 1)
        self.pushButton_Beta = QtWidgets.QPushButton(self.widget)
        self.pushButton_Beta.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_Beta.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Beta.setIcon(icon)
        self.pushButton_Beta.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Beta.setFlat(True)
        self.pushButton_Beta.setObjectName("pushButton_Beta")
        self.gridLayout_2.addWidget(self.pushButton_Beta, 0, 2, 1, 1)
        self.label_Alpha = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        self.label_Alpha.setFont(font)
        self.label_Alpha.setObjectName("label_Alpha")
        self.gridLayout_2.addWidget(self.label_Alpha, 0, 0, 1, 1)
        self.pushButton_KA = QtWidgets.QPushButton(self.widget)
        self.pushButton_KA.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_KA.setText("")
        self.pushButton_KA.setIcon(icon)
        self.pushButton_KA.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_KA.setFlat(True)
        self.pushButton_KA.setObjectName("pushButton_KA")
        self.gridLayout_2.addWidget(self.pushButton_KA, 1, 2, 1, 1)
        self.doubleSpinBox_Alpha = QtWidgets.QDoubleSpinBox(self.widget)
        font = QtGui.QFont()
        self.doubleSpinBox_Alpha.setFont(font)
        self.doubleSpinBox_Alpha.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.doubleSpinBox_Alpha.setDecimals(4)
        self.doubleSpinBox_Alpha.setMinimum(-1e+38)
        self.doubleSpinBox_Alpha.setMaximum(1e+47)
        self.doubleSpinBox_Alpha.setObjectName("doubleSpinBox_Alpha")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Alpha, 0, 1, 1, 1)
        self.doubleSpinBox_K_S = QtWidgets.QDoubleSpinBox(self.widget)
        font = QtGui.QFont()
        self.doubleSpinBox_K_S.setFont(font)
        self.doubleSpinBox_K_S.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.doubleSpinBox_K_S.setDecimals(4)
        self.doubleSpinBox_K_S.setMinimum(-1e+42)
        self.doubleSpinBox_K_S.setMaximum(1e+40)
        self.doubleSpinBox_K_S.setObjectName("doubleSpinBox_K_S")
        self.gridLayout_2.addWidget(self.doubleSpinBox_K_S, 1, 1, 1, 1)
        self.label_Alpha_Ground = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        self.label_Alpha_Ground.setFont(font)
        self.label_Alpha_Ground.setObjectName("label_Alpha_Ground")
        self.gridLayout_2.addWidget(self.label_Alpha_Ground, 2, 0, 1, 1)
        self.label_K_S = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        self.label_K_S.setFont(font)
        self.label_K_S.setObjectName("label_K_S")
        self.gridLayout_2.addWidget(self.label_K_S, 1, 0, 1, 1)
        self.pushButton_Beta_Ground = QtWidgets.QPushButton(self.widget)
        self.pushButton_Beta_Ground.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_Beta_Ground.setText("")
        self.pushButton_Beta_Ground.setIcon(icon)
        self.pushButton_Beta_Ground.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Beta_Ground.setFlat(True)
        self.pushButton_Beta_Ground.setObjectName("pushButton_Beta_Ground")
        self.gridLayout_2.addWidget(self.pushButton_Beta_Ground, 2, 2, 1, 1)
        self.label_K_S_Ground = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        self.label_K_S_Ground.setFont(font)
        self.label_K_S_Ground.setObjectName("label_K_S_Ground")
        self.gridLayout_2.addWidget(self.label_K_S_Ground, 3, 0, 1, 1)
        self.doubleSpinBox_K_S_Ground = QtWidgets.QDoubleSpinBox(self.widget)
        font = QtGui.QFont()
        self.doubleSpinBox_K_S_Ground.setFont(font)
        self.doubleSpinBox_K_S_Ground.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.doubleSpinBox_K_S_Ground.setDecimals(4)
        self.doubleSpinBox_K_S_Ground.setMinimum(-1e+43)
        self.doubleSpinBox_K_S_Ground.setMaximum(1e+47)
        self.doubleSpinBox_K_S_Ground.setObjectName("doubleSpinBox_K_S_Ground")
        self.gridLayout_2.addWidget(self.doubleSpinBox_K_S_Ground, 3, 1, 1, 1)
        self.pushButton_KA_Ground = QtWidgets.QPushButton(self.widget)
        self.pushButton_KA_Ground.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_KA_Ground.setText("")
        self.pushButton_KA_Ground.setIcon(icon)
        self.pushButton_KA_Ground.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_KA_Ground.setFlat(True)
        self.pushButton_KA_Ground.setObjectName("pushButton_KA_Ground")
        self.gridLayout_2.addWidget(self.pushButton_KA_Ground, 3, 2, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)

        self.retranslateUi(centralwidget)
        QtCore.QMetaObject.connectSlotsByName(centralwidget)

    def retranslateUi(self, centralwidget):
        _translate = QtCore.QCoreApplication.translate
        centralwidget.setWindowTitle(_translate("centralwidget", "CPE Active"))
        self.pushButton_Save.setText(_translate("centralwidget", "Ok"))
        self.pushButton_Cancel.setText(_translate("centralwidget", "Cancel"))
        self.pushButton_Beta.setToolTip(_translate("centralwidget", "<html><head/><body><p><span style=\" font-size:14pt;\">Describes the relation between resistance and reactance. More in the publication.</span></p></body></html>"))
        self.label_Alpha.setText(_translate("centralwidget", "Alpha"))
        self.pushButton_KA.setToolTip(_translate("centralwidget", "<html><head/><body><p><span style=\" font-size:14pt;\">Scaling factor of the CPE. More in the publication. More in the publication.</span></p></body></html>"))
        self.label_Alpha_Ground.setText(_translate("centralwidget", "Alpha for the Ground"))
        self.label_K_S.setText(_translate("centralwidget", "K_S"))
        self.pushButton_Beta_Ground.setToolTip(_translate("centralwidget", "<html><head/><body><p><span style=\" font-size:14pt;\">Describes the relation between resistance and reactance. More in the publication.</span></p></body></html>"))
        self.label_K_S_Ground.setText(_translate("centralwidget", "K_S for the Ground"))
        self.pushButton_KA_Ground.setToolTip(_translate("centralwidget", "<html><head/><body><p><span style=\" font-size:14pt;\">Scaling factor of the CPE. More in the publication. More in the publication.</span></p></body></html>"))

import icons_rc
import imgs_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    centralwidget = QtWidgets.QWidget()
    ui = Ui_centralwidget()
    ui.setupUi(centralwidget)
    centralwidget.show()
    sys.exit(app.exec_())

