function ea_atropos2segmask(rawSegmaskFile, anchorModality)
% Convert atropos segmask (indices ordered by intensities) to standard OSS
% segmask
% By Butenko, konstantinmgtu@gmail.com

arguments
    rawSegmaskFile      % path to segmask generated by atropos
    anchorModality      % first image used for atropos segmentation
end

rawSegmask = ea_load_nii(rawSegmaskFile);
segmask = rawSegmask;
[stim_folder,~,~] = fileparts(rawSegmaskFile);
segmask.fname = [stim_folder, filesep, 'segmask.nii'];

% we need to re-number as GM_index = 1; WM_index = 2; CSF_index = 3;
if contains(anchorModality, 'T1w')
    % csf - dark (0), grey matter - grey (1), white matter - bright (2),
    % misc (3)`
    segmask.img(segmask.img == 3) = 0;
    segmask.img(segmask.img == 0) = 3;
elseif contains(anchorModality, 'T2w')
    % white matter - dark (1), grey matter - grey (2), csf - bright (3)
    segmask.img(rawSegmask.img == 1) = 2;
    segmask.img(rawSegmask.img == 2) = 1;
else
    ea_warndlg("%s anchor modality is not supported at the moment",anchorModality)
    return
end

ea_write_nii(segmask)

