function ea_coregmr_brainsfit(options)
% uses Brainsfit to coregister MRIs.

if exist([options.root,options.patientname,filesep,options.prefs.tranii_unnormalized],'file') &&...
        ~ea_coreglocked(options,[options.root,options.patientname,filesep,options.prefs.tranii_unnormalized]) % file has already been locked and approved by used
    disp('Coregistering postop MR tra to preop MRI...');
    ea_brainsfit([options.root,options.patientname,filesep,options.prefs.prenii_unnormalized],...
                 [options.root,options.patientname,filesep,options.prefs.tranii_unnormalized],...
                 [options.root,options.patientname,filesep,options.prefs.tranii_unnormalized],...
                 options.prefs.mrcoreg.writeoutcoreg);
    disp('Coregistration done.');
end

if exist([options.root,options.patientname,filesep,options.prefs.cornii_unnormalized],'file') &&...
        ~ea_coreglocked(options,[options.root,options.patientname,filesep,options.prefs.cornii_unnormalized]) % file has already been locked and approved by used
    disp('Coregistering postop MR tra to preop MRI...');
    ea_brainsfit([options.root,options.patientname,filesep,options.prefs.prenii_unnormalized],...
                 [options.root,options.patientname,filesep,options.prefs.cornii_unnormalized],...
                 [options.root,options.patientname,filesep,options.prefs.cornii_unnormalized],...
             	 options.prefs.mrcoreg.writeoutcoreg);
    disp('Coregistration done.');
end

if exist([options.root,options.patientname,filesep,options.prefs.sagnii_unnormalized],'file') &&...
        ~ea_coreglocked(options,[options.root,options.patientname,filesep,options.prefs.sagnii_unnormalized]) % file has already been locked and approved by used
    disp('Coregistering postop MR tra to preop MRI...');
    ea_brainsfit([options.root,options.patientname,filesep,options.prefs.prenii_unnormalized],...
                 [options.root,options.patientname,filesep,options.prefs.sagnii_unnormalized],...
                 [options.root,options.patientname,filesep,options.prefs.sagnii_unnormalized],...
                 options.prefs.mrcoreg.writeoutcoreg);
    disp('Coregistration done.');
end
