function ea_write_fiducials(coords_mm,path,options)
% Small function to write fiducials (coordinates of electrode contacts) in
% Slicer3 format.
% __________________________________________________________________________________
% Copyright (C) 2014 Charite University Medicine Berlin, Movement Disorders Unit
%
% Andreas Horn

fileID = fopen(path,'w');
fprintf(fileID,['# Fiducial List file ',path,'\n',...
'# version = 2\n',...
'# name = L\n',...
'# numPoints = 8\n',...
'# symbolScale = 5\n',...
'# symbolType = 12\n',...
'# visibility = 1\n',...
'# textScale = 4.5\n',...
'# color = 0.4,1,1\n',...
'# selectedColor = 1,0.5,0.5\n',...
'# opacity = 1\n',...
'# ambient = 0\n',...
'# diffuse = 1\n',...
'# specular = 0\n',...
'# power = 1\n',...
'# locked = 0\n',...
'# numberingScheme = 0\n',...
'# columns = label,x,y,z,sel,vis\n']);

for side=1:length(coords_mm)
for coord=1:length(coords_mm{side})
    fprintf(fileID,['aK',num2str(coord+((side-1)*options.elspec.numContacts)-1),',%2.4f,%2.4f,%2.4f,%2.4f'],coords_mm{side}(coord,:));
    fprintf(fileID,'1,1 \n');
end
end

fclose(fileID);