function elmodel = ea_ossdbs_elmodel
elmodel = {'Medtronic 3389'
           'Medtronic 3387'
           'Medtronic 3391'
           'Boston Scientific Vercise'
           'Boston Scientific Vercise Directed'
           'Boston Scientific Vercise Cartesia HX'
           'Boston Scientific Vercise Cartesia X'
           'Abbott ActiveTip (6146-6149)'
           'Abbott ActiveTip (6142-6145)'
           'Abbott Directed 6172 (short)'
           'Abbott Directed 6173 (long)'
           'PINS Medical L301'
           'PINS Medical L302'
           'PINS Medical L303'
           'ELAINE Rat Electrode'
           'FHC WU Rat Electrode'
           'Medtronic B33005'
           'Medtronic B33015'
           'SceneRay SR1210'
           'SceneRay SR1200'
           'NeuroPace DL-344-3.5'
           'NeuroPace DL-344-10'
           'DIXI D08-05AM'
           'DIXI D08-08AM'
           'DIXI D08-10AM'
           'DIXI D08-12AM'
           'DIXI D08-15AM'
           'DIXI D08-18AM'};
