function elmodel = ea_ossdbs_elmodel
elmodel = {'Medtronic 3389'
           'Medtronic 3387'
           'Medtronic 3391'
           'Boston Scientific Vercise'
           'Boston Scientific Vercise Directed'
           'Abbott ActiveTip (6146-6149)'
           'Abbott ActiveTip (6142-6145)'
           'Abbott Directed 6172 (short)'
           'Abbott Directed 6173 (long)'
           'PINS Medical L301'
           'PINS Medical L302'
           'PINS Medical L303'
           'ELAINE Rat Electrode'
           'FHC WU Rat Electrode'};
