function ea_unifiedmapping_save_settings(explorer,save_as)
    % Saves the relevant settings of the tractset object to a mat file
    
    % Properties can't be saved as variables :(
    % Or with the struct flag because tractset is
    % a class and not a struct :(

    % Convert to variables first and then save
    calcthreshold = explorer.calcsettings.calcthreshold;
    posvisible = explorer.posvisible;
    negvisible = explorer.negvisible;
    showposamount = explorer.showposamount;
    shownegamount = explorer.shownegamount;
    connthreshold = explorer.statsettings.connthreshold;
    efieldthreshold_spot = explorer.statsettings.efieldthreshold_spot;
    efieldthreshold_tract = explorer.statsettings.efieldthreshold_tract;
    efieldthreshold_network = explorer.statsettings.efieldthreshold_network;

    statmetric = explorer.statsettings.statmetric;
    stimulationmodel = explorer.statsettings.stimulationmodel;
    corrtype = explorer.corrtype;
    efieldmetric = explorer.statsettings.efieldmetric;
    multitractmode = explorer.multitractmode;
    numpcs = explorer.numpcs;
    doactualprediction = explorer.doactualprediction;
    predictionmodel = explorer.predictionmodel;
    showsignificantonly = explorer.showsignificantonly;
    alphalevel = explorer.alphalevel;
    multcompstrategy = explorer.multcompstrategy;
    basepredictionon = explorer.basepredictionon;
    mirrorsides = explorer.mirrorsides;
    modelNormalization = explorer.modelNormalization;
    mask_vta_fp = explorer.mask_vta_fp;
    numBins = explorer.numBins;
    Nperm = explorer.Nperm;
    kfold = explorer.kfold;
    Nsets = explorer.Nsets;
    adjustforgroups = explorer.adjustforgroups;
    SigmoidTransform = explorer.SigmoidTransform;
    twoSampleWeighted = explorer.twoSampleWeighted;
    connectivity_type = explorer.calcsettings.connectivity_type;
    switch_connectivity = explorer.calcsettings.switch_connectivity;
    calcmethod = explorer.calcsettings.calcmethod;
    calcspace = explorer.calcsettings.calcspace;

    save(save_as,...
    "calcthreshold",...
    "posvisible",...
    "negvisible",...
    "showposamount",...
    "shownegamount",...
    "connthreshold",...
    "efieldthreshold_spot",...
    "efieldthreshold_tract",...
    "efieldthreshold_network",...
    "statmetric",...
    "stimulationmodel",...
    "corrtype",...
    "efieldmetric",...
    "multitractmode",...
    "numpcs",...
    "doactualprediction",...
    "predictionmodel",...
    "showsignificantonly",...
    "alphalevel",...
    "multcompstrategy",...
    "basepredictionon",...
    "mirrorsides",...
    "modelNormalization",...
    "mask_vta_fp",...
    "numBins",...
    "Nperm",...
    "kfold",...
    "Nsets",...
    "adjustforgroups",...
    "SigmoidTransform",...
    "twoSampleWeighted",...
    "connectivity_type",...
    "switch_connectivity",...
    "calcmethod",...
    "calcspace")
end
