ea_seed2map_weighted('/PA/Neuro/_projects/lead/lead_dbs/fibers/Groupconnectome (Horn 2013) thinned out x 500.mat',...
    {'/PA/Neuro/_projects/lead/lead_dbs/dev/seed2map/dMRI_cort_map.nii'},...
    '/PA/Neuro/_projects/lead/lead_dbs/templates/mni_hires_t2.nii');