d = {
    'Segm_MRI_processed': 0,
    'DTI_processed': 0,
    'Init_neuron_model_ready': 0,
    'Init_mesh_ready': 0,
    'Adjusted_neuron_model_ready': 0,
    'CSF_mesh_ready': 0,
    'Adapted_mesh_ready': 0,
    'Signal_generated': 0,
    'Parallel_comp_ready': 0,
    'Parallel_comp_interrupted': 0,
    'IFFT_ready': 0,
    'MRI_data_name': 'segmask.nii',
    'MRI_in_m': 0,
    'DTI_data_name': 'Johnson_WS_NormMapping.nii',
    'DTI_in_m': 0,
    'CSF_index': 3.0,
    'WM_index': 2.0,
    'GM_index': 1.0,
    'default_material': 3,
    'Electrode_type': 'AA_rodent_monopolar',
    'Brain_shape_name': '0',
    'Aprox_geometry_center': [2.476187675483748, -3.0393966740032874, -0.8115758910846853],
    'Approximating_Dimensions': [80.0, 80.0, 80.0],
    'Implantation_coordinate_X': 2.4762,
    'Implantation_coordinate_Y': -3.0394,
    'Implantation_coordinate_Z': -0.8116,
    'Second_coordinate_X': 2.4526,
    'Second_coordinate_Y': -2.9922,
    'Second_coordinate_Z': -0.1951,
    'Rotation_Z': 0.0,
    'encap_thickness': 0.1,
    'encap_tissue_type': 2,
    'encap_scaling_cond': 1.0,
    'encap_scaling_perm': 1.0,
    'pattern_model_name': '0',
    'Axon_Model_Type': 'McIntyre2002',
    'diam_fib': [2.0],
    'n_Ranvier': [5],
    'v_init': -80.0,
    'Neuron_model_array_prepared': 1,
    'Name_prepared_neuron_array': 'Allocated_axons.h5',
    'EQS_core': 'QS',
    'Skip_mesh_refinement': 1,
    'el_order': 2,
    'number_of_processors': 0,
    'FEniCS_MPI': 0,
    'current_control': 1,
    'Pulse_amp': [-0.002, 0.0],  # can be negative (i.e. cathode in VC)
    'Solver_Type': 'GMRES',
    'freq': 130.0,
    'T': 60.0,
    't_step': 1.0,
    'phi': 0.0,
    'Signal_type': 'Rectangle',
    'Ampl_scale': 1.0,
    'CPE_activ': 0,
    'VTA_approx': 0,  # !!! Here it refers to |E|-field based VTA approximation !!!
    'spectrum_trunc_method': 'Octave Band Method',
    'trunc_param': 130.0,
    'Truncate_the_obtained_full_solution': 0,
    'external_grounding': 1,
    'Stim_side': 0,
    }
