function ea_brainsfit(fixedVolume, movingVolume, outputVolume)
% Wrapper for BRAINSFit

if fileparts(fixedVolume)
    volumedir = [fileparts(fixedVolume), filesep];
else
    volumedir =['.', filesep];
end

ttries=ea_detct2anatattempts(volumedir); % how many coregistration attempts have been made in the past..

% first attempt..
fixparams{1} = [' --useRigid --useAffine' ...
    ' --samplingPercentage 0.005' ...
    ' --removeIntensityOutliers 0.005' ...
    ' --interpolationMode Linear' ...
    ' --outputTransform ', volumedir, 'ct2anat',num2str(ttries+1),'.txt'
    ' --initializeTransformMode useGeometryAlign'...
    ' --maskProcessingMode ROIAUTO' ...
    ' --ROIAutoDilateSize 3'];

% second attempt..
fixparams{2} = [' --useRigid --useAffine' ...
    ' --samplingPercentage 0.005' ...
    ' --removeIntensityOutliers 0.005' ...
    ' --interpolationMode Linear' ...
    ' --outputTransform ', volumedir, 'ct2anat',num2str(ttries+1),'.txt' ...
    ' --initializeTransformMode Off' ...
    ' --initialTransform ', volumedir, 'ct2anat',num2str(ttries),'.txt'...
    ' --maskProcessingMode ROIAUTO' ...
    ' --ROIAutoDilateSize 3'];

% third attempt..
fixparams{3} = [' --useRigid --useAffine' ...
    ' --samplingPercentage 0.005' ...
    ' --removeIntensityOutliers 0.005' ...
    ' --interpolationMode Linear' ...
    ' --outputTransform ', volumedir, 'ct2anat',num2str(ttries+1),'.txt' ...
    ' --initializeTransformMode Off' ...
    ' --initialTransform ', volumedir, 'ct2anat',num2str(ttries),'.txt'];

if ttries>3
    ttries=3;
end

basename = [fileparts(mfilename('fullpath')), filesep, 'BRAINSFit'];

if ispc
    BRAINSFit = [basename, '.exe '];
elseif isunix
    BRAINSFit = [basename, '.', computer, ' '];
end

ea_libs_helper
system([BRAINSFit, fixparams{ttries}, ...
        ' --fixedVolume ' , fixedVolume, ...
        ' --movingVolume ', movingVolume, ...
        ' --outputVolume ', outputVolume]);
delete([volumedir, 'ct2anat_Inverse.h5']);