# -*- coding: utf-8 -*-
"""
Created on Sun Oct 28 08:34:11 2018

@author: trieu,butenko
"""
import numpy as np

d = {
    'z_steps': 15,
    'encap_tissue_type': 3,
    'voxel_arr_MRI': 0,
    'default_material': 3,
    'DTI_in_m': 0,
    'el_order': 2,
    'Init_neuron_model_ready': 0,
    'Init_mesh_ready': 0,
    'Ampl_scale': 1.0,
    'y_steps': 0,
    'Implantation_coordinate_Y': -2.6281,
    'beta_array_glob': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    'YZ_angles': [0],
    'y_seed': -2.6821,
    'Implantation_coordinate_X': 2.5781,
    'y_length': 9.0,
    'Show_paraview_screenshots': 0,
    'gamma_array_glob': [0.0, 45.0, 90.0, 135.0, 0.0, 0.0, 0.0],
    'freq': 1000.0,
    'encap_scaling_cond': 0.8,
    'X_coord_old': 0,
    'spectrum_trunc_method': 'Octave Band Method',
    'trunc_param': 100000.0,
    'Name_prepared_neuron_array': 'STN_axons_Waxholm.h5',
    'CSF_mesh_ready': 0,
    'z_step': 0.1,
    'signal_generation_ready': 0,
    'Truncate_the_obtained_full_solution': 0,
    'x_steps': 15,
    'pattern_model_name': '0',
    'phi': 0.0,
    'x_length': 9.0,
    'num_ref_freqs': -1,
    'rel_div_CSF': 5.0,
    'CSF_frac_div': 5.0,
    'WM_index': 2.0,
    'current_control': 1,
    'Parallel_comp_ready': 0,
    'Min_Scaling': 1.0,
    'z_seed': -0.7,
    'K_A': 0.0,
    'K_A_ground': 0.0,
    'beta_ground': 0.0,
    'beta': 0.0,
    'Activation_threshold_VTA': 0,
    'Skip_mesh_refinement': 0,
    'IFFT_ready': 0,
    'x_step': 0.1,
    'Signal_type': 'Rectangle',
    'z_length': 6.0,
    't_step': 0.5,
    'voxel_arr_DTI': 0,
    'diam_fib': [3.0],
    'MRI_in_m': 0,
    'n_Ranvier': [15],
    'Full_Field_IFFT': 0,
    'encap_thickness': 0.05,
    'XY_angles': [0],
    'Electrode_type': 'SNEX100',
    'Implantation_coordinate_Z': -0.7,
    'Global_rot': 1,
    'Neuron_model_array_prepared': 0,
    'Adapted_mesh_ready': 0,
    'DTI_data_name': 'Waxholm_Papp_ROI_DTI.txt',
    'ZX_angles': [0],
    'Z_coord_old': 0,
    'Y_coord_old': 0,
    'CSF_index': 1.0,
    'Parallel_comp_interrupted': 0,
    'number_of_processors': 4,
    'EQS_core': 'EQS',
    'CPE_activ': 0,
    'refinement_frequency': [13130.0],
    'rel_div': 2.5,
    'Adaptive_frac_div': 2.5,   #this might be different, because we changed the adaptive refinement alg.
    'Brain_shape_name': '0',
    'encap_scaling_perm': 0.8,
    'x_seed': 2.5781,
    'rel_div_current': 2.5,
    'Adjusted_neuron_model_ready': 0,
    'Phi_vector': [0.0004, 0.0],
    'alpha_array_glob': [0.0, 0.0, 0.0, 0.0, 45, 90, 135],
    'MRI_data_name': 'Waxholm_Papp_ROI_MRI.txt',
    'CSF_ref_reg': 1.0,
    'Aprox_geometry_center': [2.5781, -2.6281, -0.7],
    'v_init': -80.0,
    'y_step': 0.1,
    'VTA_from_divE': 0,
    'VTA_from_NEURON': 0,
    'T': 20.0,
    't_step_end': 1200,
    'VTA_from_E': 0,
    'GM_index': 3.0,
    'Second_coordinate_X': 2.5781,
    'Second_coordinate_Y': -2.6281,
    'Second_coordinate_Z': 0.7,
    'Rotation_Z': 0.0,

    'Solver_Type': 'BiCGSTAB',
    'FEniCS_MPI': 0,
    'Axon_Model_Type': 'McIntyre2002',
    'Approximating_Dimensions': [9.0, 9.0, 6.0],
    }
