# -*- coding: utf-8 -*-
"""
Created on Sun Oct 28 08:34:11 2018

@author: trieu,butenko
"""
import numpy as np

d = {
    'voxel_arr_MRI': 0,
    'voxel_arr_DTI': 0,
    'Init_neuron_model_ready': 0,
    'Init_mesh_ready': 0,
    'Adjusted_neuron_model_ready': 0,
    'CSF_mesh_ready': 0,
    'Adapted_mesh_ready': 0,
    'signal_generation_ready': 0,
    'Parallel_comp_ready': 0,
    'Parallel_comp_interrupted': 0,
    'IFFT_ready': 0,
    'MRI_data_name': 'icbm_avg_152_segmented.nii.gz',
    'MRI_in_m': 0,
    'DTI_data_name': '',
    'DTI_in_m': 0,
    'CSF_index': 1.0,
    'WM_index': 3.0,
    'GM_index': 2.0,
    'default_material': 3,
    'Electrode_type': 'St_Jude6148',
    'Brain_shape_name': '0',
    'x_length': 65.0,
    'y_length': 65.0,
    'z_length': 65.0,
    'Aprox_geometry_center': [10.92957028, -12.11697637, -7.69744601],
    'Implantation_coordinate_X': 10.929,
    'Implantation_coordinate_Y': -12.117,
    'Implantation_coordinate_Z': -7.697,
    'Second_coordinate_X': 10.929,
    'Second_coordinate_Y': -9.437,
    'Second_coordinate_Z': 3.697,
    'Rotation_Z': 0.0,
    'encap_thickness': 0.3,
    'encap_tissue_type': 2,
    'encap_scaling_cond': 0.5,
    'encap_scaling_perm': 1.0,
    'pattern_model_name': '0',
    'diam_fib': [5.7, 5.7, 16.0, 5.7, 5.7, 5.7, 5.7],
    'n_Ranvier': [35, 35, 35, 30, 10, 35, 10],
    'v_init': -80.0,
    'Neuron_model_array_prepared': 1,
    'Name_prepared_neuron_array': 'Basal_ganlia_axons_corrected.h5',
    'Global_rot': 1,
    'x_seed': 2.5781,
    'y_seed': -2.6821,
    'z_seed': -0.7,
    'x_steps': 9,
    'y_steps': 0,
    'z_steps': 9,
    'x_step': 0.2,
    'y_step': 0.2,
    'z_step': 0.2,
    'alpha_array_glob': [0],
    'beta_array_glob': [0],
    'gamma_array_glob': [0],
    'X_coord_old': 0,
    'Y_coord_old': 0,
    'Z_coord_old': 0,
    'YZ_angles': [0],
    'ZX_angles': [0],
    'XY_angles': [0],
    'EQS_core': 'QS',
    'Skip_mesh_refinement': 0,
    'refinement_frequency': [13130.0],
    'num_ref_freqs': -1,
    'rel_div_CSF': -1,
    'CSF_frac_div': 1.5,
    'Adaptive_frac_div': 1.0,
    'Min_Scaling': 1.0,
    'CSF_ref_reg': 20.0,
    'rel_div': 15.0,
    'rel_div_current': 1.2,
    'el_order': 2,
    'number_of_processors': 3,
    'current_control': 1,
    'Phi_vector': [0.005, None, 0.0, None],
    'freq': 130.0,
    'T': 60.0,
    't_step': 1.0,
    'phi': 0.0,
    'Signal_type': 'Rectangle',
    'Ampl_scale': 1.0,
    'CPE_activ': 0,
    'beta': 0.0,
    'K_A': 0.0,
    'beta_ground': 0.0,
    'K_A_ground': 0.0,
    'Full_Field_IFFT': 0,
    't_step_end': 1200,
    'VTA_from_divE': 0,
    'VTA_from_NEURON': 0,
    'VTA_from_E': 0,
    'Activation_threshold_VTA': 0,
    'spectrum_trunc_method': 'Octave Band Method',
    'trunc_param': 1000.0,
    'Truncate_the_obtained_full_solution': 0,
    'Show_paraview_screenshots': 0,

    'Solver_Type': 'GMRES',
    'FEniCS_MPI': 0,
    'Axon_Model_Type': 'McIntyre2002',
    'Approximating_Dimensions': [65.0, 65.0, 65.0],
    }
