all: fig2u3d fig2pdf3d

fig2u3d:
	xelatex --interaction=nonstopmode --aux-directory=auxdir demo_fig2u3d.tex

fig2pdf3d:
	xelatex --interaction=nonstopmode --aux-directory=auxdir demo_fig2pdf3d.tex
