function ea_lcm_func(options)


if strcmp(options.lcm.func.connectome,'No functional connectome found.')
    return
end
cs_fmri_conseed([ea_getconnectomebase('fmri'),options.lcm.func.connectome,filesep],...
    options.lcm.seeds,...
    ea_lcm_resolvecmd(options.lcm.cmd),...
    '0',...
    options.lcm.odir,...
    options.lcm.omask);