function ea_lcm_struc(options)


if strcmp(options.lcm.struc.connectome,'No structural connectome found.')
    return
end
cs_dmri_conseed([ea_getconnectomebase('fmri'),options.lcm.func.connectome,filesep],...
    options.lcm.seeds,...
    ea_lcm_resolvecmd(options.lcm.cmd),...
    '0',...
    options.lcm.odir,...
    options.lcm.omask,...
    options.lcm.espace);